### ISSUE TITLE
Off-canvas: positioning opinion.

### ISSUE THREAD

**Issue by zurbchris** [zurb/foundation-sites-6#102]
Should menu's by default force the page to scroll to the top, as they do now, or adjust the menu's `top` attribute before open to keep it at the current scroll depth?

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
