### ISSUE TITLE
Off-canvas doesn't trap focus

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#115]
Off-canvas should trap focus when it opens. If you tab around in the current demo on the docs, focus will jump to the right-hand off-canvas, which is right below the left-hand one in the markup.

**Comment by gakimball** [comment]
@zurbchris Do the recent revisions to off-canvas address this?

**Comment by zurbchris** [comment]
No, but we have a method we can implement in the near future.

**Comment by gakimball** [comment]
Reopening at zurb/foundation-sites#7666
