### ISSUE TITLE
Foundation 6 Building Blocks

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#118]
Hello friends.

ZURB maintains a collection of code snippets called [Building Blocks](http://zurb.com/building-blocks). Before this framework launches, we want to overhaul the entire set, writing them all in Foundation 6, and also making each one less stylistically complex.

Foundation 6 is all about modularity and smaller components, so we want Building Blocks to be a repository of code snippets that show you how to combine F6's simpler components into bigger pieces. Here are some examples:

- Re-creating Foundation 5's Top Bar using the new Menu Bar and Responsive Menu
- A nested comment thread using the Media Object
- Complex forms that use the grid and inline input groups

**If you have ideas for Building Blocks, *or* if you want to write some yourself, let us know!** We don't have a formal submission process right now, so let's collect ideas here. A Building Block is just a chunk of HTML, CSS, and maybe light JavaScript. Visually it should still look like stock Foundation for the most part.

**Comment by wtsutton** [comment]
A combined Tabs and Accordion seems to work on Foundation 6. The tabs show medium up and the accordion on small only.

    
    <ul class="tabs show-for-medium" data-tabs="data-tabs" id="example-tabs">
      <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Panel 1</a></li>
      <li class="tabs-title"><a href="#panel2">Panel 2</a></li>
      <li class="tabs-title"><a href="#panel3">Panel 3</a></li>
    </ul>
    <ul class="accordion tabs-content" data-tabs-content="example-tabs" 
             data-accordion="data-accordion" role="tablist">
      <li class="accordion-item is-active">
        
        <a class="show-for-small-only" href="#panel1" role="tab" class="accordion-title" 
                id="panel1-heading" aria-controls="panel1">Panel 1</a>
        
        <div id="panel1" class="accordion-content tabs-panel is-active" role="tabpanel" 
                 data-tab-content="data-tab-content" aria-labelledby="panel1-heading">
          <p>Panel 1. This is the first panel. This is the first panel. This is the first panel. 
                  This is the first panel.</p>
        </div>
      </li>
      <li class="accordion-item">
        
        <a class="show-for-small-only" href="#panel2" role="tab" class="accordion-title" 
                 id="panel2-heading" aria-controls="panel2">Panel 2</a>
        
        <div id="panel2" class="accordion-content tabs-panel" role="tabpanel" 
                      data-tab-content="data-tab-content" aria-labelledby="panel2-heading">
          <p>Panel 2. This is the second panel. This is the second panel. This is the second panel. 
                      This is the second panel.</p>
        </div>
      </li>
      <li class="accordion-item">
        
        <a class="show-for-small-only" href="#panel3" role="tab" class="accordion-title" 
                   id="panel3-heading" aria-controls="panel3">Panel 3</a>
        
        <div id="panel3" class="accordion-content tabs-panel" role="tabpanel" 
                   data-tab-content="data-tab-content" aria-labelledby="panel3-heading">
          <p>Panel 3. This is the third panel. This is the third panel. This is the third panel. 
                          This is the third panel.</p>
        </div>
      </li>
    </ul>

**Comment by JeremyEnglert** [comment]
Here's a better version of the "Foundation 5" style nav.

http://jointswp.com/f6/

````HTML
       <div class="top-bar">
		  <div class="top-bar-left float-left">
		    <ul class="menu">
		      <li class="menu-text">Site Title</li>
		    </ul>
		  </div>
		  <div class="top-bar-right show-for-medium">
		     <ul class="dropdown menu" data-dropdown-menu>
		      <li class="has-submenu">
		        <a href="#">Oned</a>
		        <ul class="submenu menu vertical" data-submenu>
		          <li><a href="#">One</a></li>
		          <li><a href="#">Two</a></li>
		          <li><a href="#">Three</a></li>
		        </ul>
		      </li>
		      <li><a href="#">Two</a></li>
		      <li><a href="#">Three</a></li>
		    </ul>
		  </div>
		  <div class="top-bar-right float-right show-for-small-only">
		     <ul class="menu">
		      <li><a data-toggle="offCanvas">Menu</a></li>
		    </ul>
		  </div>
		</div>
````

**Comment by gakimball** [comment]
Hey friends, thanks for all the suggestions :) We're about to finalize our initial list of shipping building blocks, but there will be avenues for folks to contribute new ones in the future.
