### ISSUE TITLE
Idea: rename js/foundation.core.js to js/foundation.00-core.js

### ISSUE THREAD

**Issue by pwnall** [zurb/foundation-sites-6#120]
This would make it so that sorting the files in js/foundation gets them in a correct inclusion order. This makes it easy to automate packaging, which would avoid things like the recurring require order issue that has been plaguing foundation-rails 5.5.
https://github.com/zurb/foundation-rails/pull/126

The name looks a bit ugly, but folks familiar with unix drop-in configuration directories will immediately understand it. Also, FWIW, I used this approach in dropbox.js, and nobody complained.
https://github.com/dropbox/dropbox-js/tree/stable/src

**Comment by gakimball** [comment]
We ended up not taking this approach. In general we don't want to encourage too much automatic loading of files, as the order is important.

In our Gulp build process, we use this set of globs, in this order:

```
js/foundation.core.js
js/foundation.util.*.js
js/foundation.*.js
```

This puts every file in the proper order. If you can replicate functionality like this in Rails, you'll be good.

When we get to updating foundation-rails for F6, we'll make sure we've got our bases covered there.
