### ISSUE TITLE
Idea: rails packaging

### ISSUE THREAD

**Issue by pwnall** [zurb/foundation-sites-6#121]
I'm building a Rails application with Foundation for Sites 6. I created a copy of the foundation-rails repository, and I wrote a rake task that vendors foundation 6 into the gem, given the directory of a Foundation 6 checkout.

The rake task can be merged into the foundation-rails repository without exposing the Foundation for Sites 6 source code. This would let other folks follow my vendoring approach with very little effort.

Should I submit a PR for this, or would you prefer that everything related to Foundation 6 is completely closed off?

My Rake task is below.

```ruby
require 'fileutils'

desc 'Copy the files from a Foundation 6 distribution to vendor/'
task :import6 do
  base = ENV['DIR']
  unless base && File.exist?(base)
    puts 'Could not find Foundation distribution directory'
    exit 1
  end

  FileUtils.rm_r 'vendor'
  FileUtils.mkdir_p 'vendor/assets/javascripts/foundation'
  FileUtils.mkdir_p 'vendor/assets/stylesheets'

  js_files = Dir.entries(File.join(base, 'js')).sort.select do |entry|
    !File.directory? File.join(base, 'js', entry)
  end
  # foundation.core must be loaded before the rest of the JS files.
  js_files.delete 'foundation.core.js'
  js_files.unshift 'foundation.core.js'

  File.open 'vendor/assets/javascripts/foundation.js', 'wb' do |f|
    js_files.each do |file|
      f.write "//= require foundation/#{file}\n"
      FileUtils.cp File.join(base, 'js', file),
                   'vendor/assets/javascripts/foundation'
    end
  end

  FileUtils.cp_r File.join(base, 'scss'), 'vendor/assets/stylesheets/'
  FileUtils.mv 'vendor/assets/stylesheets/scss',
               'vendor/assets/stylesheets/foundation'
end
```

Adding it also requires a one-line addition to the bottom of the `Rakefile`.

```ruby
import 'tasks/import.rake'
```

The PR diff would add the code I wrote above.

What do you think?

**Comment by tdhartwick** [comment]
Marking as closed!
