### ISSUE TITLE
Responsive Navigation Pattern Issues

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#126]
I've been doing some testing with the different responsive navigation patterns and have documented the different issues I have found here: http://jointswp.com/f6/

Most of the issues are small, however, one that may become troublesome are the .vertical and .horizontal classes that belong to .menu-bar. The .vertical and .horizontal classes are applied to navigation items regardless of the screen size. 

This makes it extremely difficult to use the dropdown and drilldown menu's together as dropdown looks best with a horizontal alignment and drilldown looks best with a vertical alignment. If you look at number 3 on the link above, you will see what I mean.

It would be awesome to have classes that are specific to different screen sizes. So something like ".horizontal-on-small" and ".vertical-on-small" would resolve this issue.

**Comment by JeremyEnglert** [comment]
The .vertical class having a width of 100px seems to be causing some issues when using the responsive navigation in the right-topbar section.

![screen shot 2015-11-08 at 9 54 18 pm](https://cloud.githubusercontent.com/assets/6110968/11028699/1ded55cc-867e-11e5-92d8-7a8b7cc4d502.png)

**Comment by johanhatlehols** [comment]
I am experiencing the same issues. Any progres on this?

**Comment by gakimball** [comment]
Hey guys, we're closing this repo today so we can keep everyone focused on the main one. We have a number of open issues related to Responsive Navigation right now, which we'll be addressing in the near future. Thanks again for helping us find bugs! :)
