### ISSUE TITLE
Magellan: Scrolls to wrong position

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites-6#133]
i got a sticky magellan navigation on the right and magellan targets left (as on docs)
the left side is 2000px height the right side is 1000px height
for example my first target is at 200px i click on the right magellan the first target now is scrolls completle to top because
```js
var arrival   = $(this).attr('href'),
            navOffset = self.$element.height();

        $('html, body').animate({
          scrollTop: $(arrival).offset().top - navOffset
        },
        {
          duration: self.options.animationDuration,
          easing:   self.options.animationEasing
        });
```
$(arrival).offset().top is 200px and navOffset is 1000px so it tries to scroll to -800px
why the navOffset is subtracted from the $(arrival).offset().top?

even i the docs page for example button.html the scroll is to the wrong position.

**Comment by zurbchris** [comment]
This should be resolved on the develop branch. Thanks for the feedback, and if you see any other issues, please let us know.
