### ISSUE TITLE
flex-grid-row mixin confusion

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites-6#141]
Hello
Maybe I'm missing something but I ran into the following issue:

I'm able to pass a gutter width to the flex-grid-column mixin which results in padding-left and padding-right - in order to make up for the left/right padding the margin of the row set to a negative margin - I get that - however I don't see a way to pass a custom gutter width to the flex-grid-row mixin in order to correspond with the custom gutter width used in the flex-grid-column mixin - the row mixin seems to always use the default gutter width?

**Comment by mmjaeger** [comment]
any progress on this one?

**Comment by mmjaeger** [comment]
I'm a little surprised this hasn't been fixed before the release yesterday - am I missing something here?

**Comment by mmjaeger** [comment]
is this going to be fixed any time soon or what's your thought on this issue

**Comment by gakimball** [comment]
Yes, we'll be addressing this for the float grid and flex grid soon. Going to track this issue at zurb/foundation-sites#7115
