### ISSUE TITLE
Off-canvas - menu icon container needs to have a "fixed" option

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites-6#146]
We need to make sure that if someone wants to make the off-canvas bar stay fixed to the top, and then when the menu icon is clicked, the menu open without scrolling to the top.

**Comment by gakimball** [comment]
@zurbchris Do the recent revisions to off-canvas address this?

**Comment by zurbchris** [comment]
Not keeping a menu bar fixed, no. Transitioned elements and position:fixed and whatnot. Though I can think of a few things to fix it in the future.

**Comment by gakimball** [comment]
Due to ***browser bug madness*** 6.0.0 didn't ship with this, but it will return... *someday*.

**Comment by zurbchris** [comment]
:crying_cat_face: :sob:

**Comment by blynnc** [comment]
No need to sob.  Take action!

**Comment by zurbchris** [comment]
It is in the code base currently, just commented out because safari doesn't handle scroll events in a logical fashion and ie >= 9 doesn't support `transform: translate(x,x);`

**Comment by zurbchris** [comment]
It's gorgeous on Chrome/FireFox/IE 10+

**Comment by blynnc** [comment]
Thanks for all the great work! and making Foundation Leaner, meaner and Cleaner! -- and free! and so easy to customize. I am getting started now on some projects with the NEW FONDATION.
