### ISSUE TITLE
Integrate Outline.js (or something similar) to Remove Outline Styling

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#153]
Outlines around links are very important for accessibility, however, they aren't the greatest looking elements and often clash with website designs.

I fear that most developers/designers are going to use 'outline:none' to remove the outline, which also throws accessibility out the window.

Outline.js by Lindsay Evans addresses this issue by only displaying outlines on keyboard events:
https://github.com/lindsayevans/outline.js/blob/master/outline.js

**Comment by gakimball** [comment]
Merged #199 which implements what-input. We also made a handy mixin to quickly add the feature to any element:

```scss
.button {
  @include disable-mouse-outline;
  // ...
}
```
