### ISSUE TITLE
Off-Canvas: buggy on android device

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites-6#154]
I tried the docs on a Android Device in the default Browser.
the Right Canvas is reachable by default if i scroll to the right the canvas is visible

toggeleing the right canvas with the button is buggy too, off canvas opens but is twice the width and all white.

**Comment by gakimball** [comment]
We eventually got this working well in Android 2 and 4 for the initial 6.0.0 release. If you encounter any more issues with off-canvas in the stable release, let us know with a new issue at [zurb/foundation-sites](https://github.com/zurb/foundation-sites). Thanks!
