### ISSUE TITLE
[Media Object] Browser inconsistencies

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites-6#167]
I have been trying out media object in what I think it would be perfect for: comments. I've added it to a WordPress theme to test. 

There are a few issues I've found depending on browser. I've tested in Chrome and Firefox, but Edge results are the same as Chrome.

* Avatars shrink in Chrome depending on how wide the content is - the wider the content the smaller the avatar. Firefox doesn't have this issue, they are consistent.
* Content overflowing its container. In Firefox the image overflows the container, whilst in Chrome it fits within it nicely.

Hopefully this quick image should help to illustrate the issue.

![media object issues](https://cloud.githubusercontent.com/assets/73229/10709956/b020d8d4-7a39-11e5-8e85-36d35a3f9751.png)

**Comment by rafibomb** [comment]
Should be max-width: none; to preserve the natural image size. Fixed on develop 774a798
