### ISSUE TITLE
[Dropdown Menus] Menu item links don't work

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites-6#171]
No links on a dropdown menu item seem to work.

In the below screenshot the About link works correctly, but no other link in the menu works (top level or in sub menu). Also mentioned in [this](https://github.com/zurb/foundation-sites-6/issues/170) issue.
![dropdown](https://cloud.githubusercontent.com/assets/73229/10765738/2df2a26c-7ccc-11e5-9ce9-c6ff3d36cf98.png)

**Comment by zurbchris** [comment]
This has been resolve on the develop branch. By default, dropdowns have `clickOpen` set to true, setting this to false allows links with submenus to be accessed like normal links.
