### ISSUE TITLE
Button groups have visual border quirk

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation-sites-6#172]
![image](https://cloud.githubusercontent.com/assets/67395/10766639/a5cff32a-7c95-11e5-90af-13fe68a4bb5a.png)
So the fact that in a button group all the right borders are white (in order to create the gap) creates a weird visual quirk with the border-radius. I realize that inline-block is not normally super susceptible to margins, but in this case I think using a 1px margin instead of a white border would be smarter.

I found a lot of frustrations with how borders were utilized in f5 and was required to completely rewrite the buttons mixins because borders are explicitly used to create buttons, even though they don't appear visually on the screen. The problem with this is that if you actually WANT borders to appear on buttons, you have to do a LOT of css overriding and it was just easier to write a lighter mixin.

Any thoughts on removing border css from buttons? Should I file another ticket?

**Comment by gakimball** [comment]
Reopening at zurb/foundation-sites#7665 so we can close this repo today.
