### ISSUE TITLE
Split Button visual quirk

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation-sites-6#173]
![image](https://cloud.githubusercontent.com/assets/67395/10767757/f502d34a-7c9a-11e5-8399-4b11f8bea4bc.png)
Note that the arrow-only doesn't match the dimensions of the button next to it. Honestly, I don't really see a point in the `arrow-only` class. You could use a more composeable (and therefore customizable, and less prone to bugs) solution, which I believe is what bootstrap does:
```
<div class="button-group">
  <a class="button">Primary Action</a>
  <a class="dropdown button">
    <i class="fi-arrow-down"></i>
    <span class="show-for-sr">Show menu</span>
  </a>
</div>
```
![image](https://cloud.githubusercontent.com/assets/67395/10767824/5f965466-7c9b-11e5-980e-d58a79e3119d.png)

**Comment by tdhartwick** [comment]
Switched the after element to `display:inline-block;` instead of `display:block;`. Fixed here: https://github.com/zurb/foundation-sites-6/commit/08f8a66e71c6d926c505c9c1533653adc3e40a94
