### ISSUE TITLE
More customizeable button styles

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation-sites-6#175]
So at our company we started playing around with `hollow` type buttons. However we only made 1 palette (`.secondary`) the "hollow" style while all other palettes appeared normally. The key purpose of this style was to give the button 2 states: active and inactive. It would appear grey when inactive and then it would appear blue when active (making it a checkbox-esque behavior).

I do like having hollow in multiple palettes and the introduction of this class, however what if we refer to this style as `inverted` which I believe touches on an important design point:

_Instead of describing how the button looks necessarily, we are describing how it differs from standard buttons_

### What if we could make "hollow" the default button style?

By this I mean, if you had some sort of SASS variable toggle allowing us to specify which one is default and therefore we could simply apply an `inverted` class to get the secondary visual style.

Here is a simple visual example of how we did this, however it does not exactly fall into your hollow palettes:
![image](https://cloud.githubusercontent.com/assets/67395/10768466/81e83766-7c9e-11e5-879b-83e77fb604d9.png)

You may also note that we introduced a `.square` class and a `.circle` class to provide us some more style variations

**Comment by gakimball** [comment]
Reopened at zurb/foundation-sites#7557
