### ISSUE TITLE
Feedback: Navigation Patterns

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#18]
For Foundation 6 we're trying to make our navigation patterns more flexible. Top Bar is a great plugin for the *one thing* it does, but it tends to be inflexible. **Our goal for Foundation 6 is to have a series of smaller nav patterns that can be combined based on the needs of your design.**

Here are the pieces:

- Menu Bar: a stock menu component with orientation, spacing, and alignment options.
- Menu Bar plugins:
  - Dropdown menu
  - Drilldown menu
  - Accordion menu
- A responsive menu bar plugin that allows a menu to convert from one of the above patterns to another, depending on screen size.
- Top Bar: a simple wrapper to combine menus with logos, text fields, buttons, and so on.

Here's a basic example from the documentation that places a dropdown menu within a top bar.

```html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu-bar" data-dropdown-menu>
      <li class="has-submenu">
        <a href="#">One</a>
        <ul class="submenu menu-bar vertical" data-submenu>
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <li><a href="#">Three</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu-bar">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>
```

Here's an example of a responsive menu, which is a drilldown on mobile and a dropdown on larger screens. Note the `data-menu-bar` attribute which defines which plugins are used, and on what screen size.

```html
<ul class="vertical menu-bar" data-menu-bar="drilldown medium-dropdown">
  <li class="has-submenu">
    <a href="#">Item 1</a>
    <ul class="vertical submenu menu-bar" data-submenu id="m2">
      <li class="has-submenu">
        <a href="#">Item 1A</a>
        <ul class="vertical submenu menu-bar" data-submenu id="m3">
          <li><a href="#">Item 1A</a></li>
          <li><a href="#">Item 1B</a></li>
          <li><a href="#">Item 1C</a></li>
          <li><a href="#">Item 1D</a></li>
          <li><a href="#">Item 1E</a></li>
        </ul>
      </li>
      <li><a href="#">Item 1B</a></li>
    </ul>
  </li>
  <li class="has-submenu">
    <a href="#">Item 2</a>
    <ul class="vertical submenu menu-bar" data-submenu>
      <li><a href="#">Item 2A</a></li>
      <li><a href="#">Item 2B</a></li>
    </ul>
  </li>
  <li class="has-submenu">
    <a href="#">Item 3</a>
    <ul class="vertical submenu menu-bar" data-submenu>
      <li><a href="#">Item 3A</a></li>
      <li><a href="#">Item 3B</a></li>
    </ul>
  </li>
</ul>
```

**We'd like feedback on how Foundation can help you build navigation.**

**Comment by JeremyEnglert** [comment]
Being able to navigate to the top level items in the accordion would be awesome.

**Comment by blynnc** [comment]
Nevermind Awesome. It's a neccessity.

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
