### ISSUE TITLE
Outline stroke when hovering a dropdown element

### ISSUE THREAD

**Issue by olefredrik** [zurb/foundation-sites-6#181]
What's the deal with the blurry outline strokes when hovering a dropdown element? The stroke on "one" doesn't disappear when hovering "two" or "three". Feels weird. The issue seems to be triggered by the tabindex value on the list item. Is it possible to retain accessibility considerations and tabindex functionality without getting major visual outlines of all the elements that have a tabindex value attached to it?

![outline-stroke](https://cloud.githubusercontent.com/assets/1080017/10870333/64415dd6-80c8-11e5-8464-a61141538b06.png)

OSX El Capitan, Chrome 46.0.2490.80

**Comment by gakimball** [comment]
Merged #199 which implements what-input and removes this dropdown outline if the user is using a mouse. It still shows up on keyboard use.
