### ISSUE TITLE
[Flex Grid] Docs Typo

### ISSUE THREAD

**Issue by jbrooks619** [zurb/foundation-sites-6#192]
In your documentation for the BASICS of the flex-grid you have:

```html
<div class="row">
  <div class="small-6 columns">6 columns</div>
  <div class="small-6 columns">6 columns</div>
</div>
<div class="row">
  <div class="medium-6 large-4 columns">12/6/4 columns</div>
  <div class="medium-6 large-8 columns">12/6/6 columns</div>
</div>
```

I think that should be: 
```html
<div class="row">
  <div class="small-6 columns">6 columns</div>
  <div class="small-6 columns">6 columns</div>
</div>
<div class="row">
  <div class="medium-6 large-4 columns">12/6/4 columns</div>
  <div class="medium-6 large-8 columns">12/6/8 columns</div>
</div>
```

so that the last div shows that on Large Screens the last div would take up 8 columns, not 6.

**Comment by gakimball** [comment]
It's all good, I've got you! 17202629bb07e81a663c28e47c45df0c24ced2ea

**Comment by jbrooks619** [comment]
yeah i was looking into all that. Very new to all the things you can do on
github.... ><

 Thanks

**Comment by gakimball** [comment]
@jbrooks619 For simple changes like typos, there's a really easy way to submit pull requests. You can open any file here on GitHub and click the edit link (pencil icon) in the top right corner. From there you can make your edits, and at the bottom will be a form to submit the change as a pull request. [Here's the page](https://github.com/zurb/foundation-sites-6/edit/develop/docs/pages/flex-grid.md) for editing the flex grid docs, as an example.

**Comment by jbrooks619** [comment]
Man, I really appreciate the help. Wish I could have gotten that in. I
havent ever had the need to use github much as most of my skills are self
taught. Its nice to meet some people willing to help. Thanks again and hit
me up anytime. @JBrooks_Design on twitter if you are on there or email me.

**Comment by gakimball** [comment]
@jbrooks619 Don't worry, there will be many, *many* typos in the future for you to fix for us ;)
