### ISSUE TITLE
Bug: Accordion doesn't work in interchange

### ISSUE THREAD

**Issue by ucreate-us** [zurb/foundation-sites-6#194]
I am using interchange to switch out some content areas and I noticed that if I put the sample accordions within interchange content (separate HTML) they will not function. If I plop that same code out of an accordion it works fine.

Note: I also reported another bug with accordions containing `a` elements.

**Comment by gakimball** [comment]
@zurbchris This might be an instance where the plugin should be doing that reflow action for the developer. I can implement it and see how it works.

**Comment by ucreate-us** [comment]
@gakimball that would be helpful. I know I didn't see anything about reflow in the docs and didn't know if that was deprecated. Seems to me with the efficiencies of F6 that more people will use interchange. We will be implementing a pretty expansive site so getting interchange to work with plugins on a global scale (reflow all rather than individual plugins) would be beneficial.

I did try the listener and it writes to the console log during resize, but is failing when I try to initialize foundation with it (I don't have the error handy but I recall something about "match"). I am not the best JS developer admittedly so I could have been doing something wrong.

**Comment by zurbrandon** [comment]
Yeah, Interchnage would benefit a ton to be able to reflow content as it comes in. This would be a huge win for it.

**Comment by zurbchris** [comment]
We'll make it happen.

**Comment by gakimball** [comment]
Reopened at zurb/foundation-sites#7559
