### ISSUE TITLE
Feedback: Sass exports

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#20]
For Foundation 6, we're changing how CSS is exported to hopefully be simpler to understand.

**Simply importing the framework doesn't output CSS.** This makes it easy to `@import` the entire framework and not worry about which pieces you want right away.

Compile times may be a concern, but the increasing robustness of libsass makes the compile times negligible.

**CSS exports are handled through mixins.** So a stock `app.scss` might look like this:

```scss
@import 'settings';
@import 'foundation';

@include foundation-global-styles;
@include foundation-grid;
@include foundation-button;
// And so on...
```

This also allows components to be namespaced.

```scss
#foundation {
  @include foundation-grid;
}
```

**Comment by erutan** [comment]
I'd generally only include the components I'd need, and turn off CSS rendering for everything that didn't deal with the element level (typo, forms, etc), so this definitely makes life easier!

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
