### ISSUE TITLE
Topbar button height doesn't match input height

### ISSUE THREAD

**Issue by codymorgan** [zurb/foundation-sites-6#207]
In your doc example http://foundation.zurb.com/sites-6-docs/top-bar.html, the button for the search form in the topbar doesn't match the height of the input field.looks like its off by a pixel due to the border calculation on the input field itself.

**Comment by zurbchris** [comment]
Thanks, I'll send this on over to @gakimball who would likely be the best guy to have a look.

**Comment by gakimball** [comment]
We had this issue in Foundation 5, and it's difficult to solve for because different browsers handle pixel rounding differently. As a result, we get it *close*, but it's difficult to get perfect.
