### ISSUE TITLE
Feedback: Documentation 

### ISSUE THREAD

**Issue by zurbrandon** [zurb/foundation-sites-6#21]
For Foundation 6 we're trying to make our documentation more robust and easier to navigate. We've made a bunch of improvements with the layout and build system.

Here are the new features we're adding:
- **Prominent Search**: We've made the search bar more prominent at the head of the page and have it auto focusing, so you can quickly search for components. It also now searches for not only component names and aliases, but also variable names, mixins and functions.
- **Page Sidebar**: We've added a sidebar for every page that shows what can be found on that as well as take you to those section. *Note: The sticky sidebar is still being worked on and may be slightly buggy* 
- **Contribute**: Each page now has links to open an issue for that component, update the documentation with a PR and see the source code. 
- **Sass & JS Documentation**: We're auto generating our the bottom of every page with the Sass variables, functions and mixins. 

We're interested to find out if these new features are enhancing your experience with the docs or if they are making it more difficult to navigate. Do they feel they are more complete than the current docs? Anything else you'd suggest adding?

**Comment by Tinkerism** [comment]
Great work! Thanks a lot. Is there any place to report spelling mistakes or missing links to? This feedback page seems not to be the right place for it.

**Comment by gakimball** [comment]
@Tinkerism You can open issues or write pull requests with the typos fixed. :)

**Comment by oxocode** [comment]
I've submitted a PR for typos I've found while navigating the Sass docs.

I definitely like the Prominent Search enhancements made to include allthesassthings. But, I must admit that I didn't notice the enhancement until I read this thread. When the blue callout box re: beta is removed, it may be easier to spot. 

While redundant, I do think it would be helpful to include a list on the main Sass doc that references...all of the references. :grinning:

**Comment by oxocode** [comment]
After looking at the new docs search again, I submitted a [PR](https://github.com/zurb/foundation-sites-6/pull/240) to make the search even more prominent. :smiley:

https://github.com/zurb/foundation-sites-6/pull/240

Thoughts?

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
