### ISSUE TITLE
How does this affect the old version of Foundation?

### ISSUE THREAD

**Issue by holisticnetworking** [zurb/foundation-sites-6#210]
My concern is this: I want to try out the new version of Foundation, but after I install it, the beta version's shell command is the same as that of the stable version. I don't want to mess with my production work in order to try out this version.

Can this version be aliased in a way that allows me to work with both at the same time?

**Comment by zurbrandon** [comment]
Yeah, this will remove the old version. For now we're not namespacing, so you may want to avoid using the cli for 6.

You can still set up the docs and it comes with a test bed as laid out in the read me if you'd like to play around still.

**Comment by tdhartwick** [comment]
Marking as closed.
