### ISSUE TITLE
Foundaton 6 Orbit image missing and observations

### ISSUE THREAD

**Issue by adamos42** [zurb/foundation-sites-6#211]
From the documentation the "http://foundation.zurb.com/assets/img/interchange/small.jpg" image is missing and the orbit height wrong. It should be nice if the first image is not available then use the next available during the initialization. Also the jQuery.event.dispatch is generating janks, the event distpacth and the listener are seriusley slow, and after that the style change not waiting a frame.
http://foundation.zurb.com/sites-6-docs/orbit.html

**Comment by adamos42** [comment]
Also because the image missing the http://foundation.zurb.com/sites-6-docs/sticky.html page has no sticky image to show :)

**Comment by tdhartwick** [comment]
Thanks for pointing this out! We adjusted the asset paths in these commits: https://github.com/zurb/foundation-sites-6/commit/c07a134368ec0a10205eb258a4dd5a10a08284a7 and https://github.com/zurb/foundation-sites-6/commit/487f86ce1cfe9aea8ce871761a6c2c949fb0c998. It'll update the next time we push the docs!
