### ISSUE TITLE
Advanced Projects - Deprecated Button Classes

### ISSUE THREAD

**Issue by Ethanhackett** [zurb/foundation-sites-6#214]
I'm not sure if round/radius classes are supposed to be part of Foundation 6 or not but the Advanced Project (Download Advanced Template - https://github.com/zurb/foundation-ssg/archive/master.zip) includes button examples for "Radius" and "Round" but the button documentation doesn't mention either class so I'm assuming they're being deprecated?

http://foundation.zurb.com/sites-6-docs/starter-projects.html#advanced-project

**Comment by pixelspring** [comment]
Yes, the radius and round classes are being dropped - more info in 3rd comment here:
https://github.com/zurb/foundation-sites-6/issues/60

**Comment by Ethanhackett** [comment]
It looked like they were being removed but I was confused when I saw it in the Advanced Template had them and lacked the css.
![screen shot 2015-11-06 at 2 39 42 pm](https://cloud.githubusercontent.com/assets/480564/11006878/3a8cf66a-8494-11e5-8911-20bf81de74d1.png)

**Comment by Ethanhackett** [comment]
I created a pr to fix - https://github.com/zurb/foundation-ssg/pull/6

**Comment by zurbrandon** [comment]
Ah thanks @Ethanhackett!

**Comment by rafibomb** [comment]
@Ethanhackett Can you apply the PR to this repo? We'd love to merge it in.
