### ISSUE TITLE
[Right-to-Left Support] Japanese is not right-to-left language.

### ISSUE THREAD

**Issue by HiroKws** [zurb/foundation-sites-6#215]
See http://www.i18nguy.com/temp/rtl.html 

Normally Japanese write left to right. At very old style writing, just right to left.
On Japanese web page, 100% left to right.

**Comment by HiroKws** [comment]
Need correct the document page.

**Comment by zurbrandon** [comment]
Just did a push on our develop branch for this! Thanks!
