### ISSUE TITLE
Changing $header-sizes map values in _settings.scss files doesn't do anything

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites-6#219]
When I try to change the $header-sizes map in the _settings.scss file, the header sizes don't change. 

```sass
$header-sizes: (
  small: (
    'h1': 24,
    'h2': 20,
    'h3': 19,
    'h4': 18,
    'h5': 17,
    'h6': 16,
  ),
  medium: (
    'h1': 48,
    'h2': 40,
    'h3': 31,
    'h4': 25,
    'h5': 20,
    'h6': 16,
  )
);
```

It seems odd that "small" and "medium" are the options—is that intentional? Any help is much appreciated.

**Comment by zurbrandon** [comment]
Yeah, just tried it. I'll check it out

**Comment by gakimball** [comment]
The variable was missing a `!default` flag; #257 fixes this.

**Comment by designerdean** [comment]
I'm still getting an error (attached). What am I doing wrong? Can you not use the rem-calc function in this header map?
![screen shot 2015-11-11 at 2 20 07 pm](https://cloud.githubusercontent.com/assets/729893/11103399/6f5e12a4-887f-11e5-81f3-80bb248bebcf.png)

**Comment by designerdean** [comment]
I apologize—I see now that it does already to rem-calc() by default, so I was essentially making it perform rem-calc() on rem-calc(). Sorry!

**Comment by gakimball** [comment]
@designerdean That's probably worth clarifying in the documentation.

Or the `rem-calc()` function should be updated to just pass through `rem` values as-is.

**Comment by designerdean** [comment]
Great point. From my perspective, either would be great.

**Comment by gakimball** [comment]
@designerdean To track it: #277

**Comment by designerdean** [comment]
Thanks, @gakimball
