### ISSUE TITLE
Feedback: Flexbox Grid

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#22]
Foundation 6 will have an optional flexbox grid, which can be used in place of the float grid. (If you use the mixins only, you could even combine them!) Here's what it looks like.

**The core syntax is the same.** Columns without a sizing class will use flexbox's expand behavior.

```html
<div class="row">
  <div class="column">33% width</div>
  <div class="column">33% width</div>
  <div class="column">33% width</div>
</div>
```

**Columns can shrink.** Add a `.shrink` class and a column will use flexbox's shrink behavior.

```html
<div class="row">
  <div class="column shrink">Small column!</div>
  <div class="column">Large column!</div>
</div>
```

**Columns can be sized with percentages.** The same 12-column grid is used. Columns with no size will fill the leftover space.

```html
<div class="row">
  <div class="small-6 column">50% width</div>
  <div class="column">25% width</div>
  <div class="column">25% width</div>
</div>
```

**A row can auto-unstack on certain screen sizes.** In the below example, the six columns stack on small, and appear side-by-side, even-width, on medium and up.

```html
<div class="row medium-unstack">
  <div class="columns">One</div>
  <div class="columns">Two</div>
  <div class="columns">Three</div>
  <div class="columns">Four</div>
  <div class="columns">Five</div>
  <div class="columns">Six</div>
</div>
```

**Columns can be horizontally and vertically aligned.** We have helper classes for flexbox's `align-items`, `align-self`, and `justify-content`.

```html
<div class="row align-right align-bottom">
  <div class="column small-4">Aligned to</div>
  <div class="column small-4">the right</div>
</div>
```

**Columns can be (responsively) source ordered.** These use the flexbox `order` property.

```html
<div class="row">
  <div class="column order-2 medium-order-1"></div>
  <div class="column order-1 medium-order-2"></div>
</div>
```

**Comment by gakimball** [comment]
@ucreate-us The breakpoint issue was fixed earlier this week.

@Tschef The Apps grid has a few fundamental issues that we still haven't fully worked out, including:

- How browsers handle scrolling inner panels, and not an entire window
- How the keyboard interacts with the grid frame (mobile browsers handle this differently)
- Working with scroll events/positioning when the browser isn't scrolling the whole window
- The class naming and structure is confusing to developers

The Apps grid is more about carving up a screen into fixed-position sections, while the Sites grids are still built around the 12-column responsive paradigm. For that reason, along with the issues described above, we didn't want to just port over the Apps grid to Sites.

I'm not sure what you mean by class name fragmentation, though, because the two Sites grids use the same core syntax. The flex grid adds new classes for its exclusive features.

**Comment by Tschef** [comment]
@gkambill

Thanks for the extensive answer and explanation. That explains the thought process very well.

With class name fragmentation i meant the different names in F4A and F64S (Foundation 6 for sites), not between the 2 grids in F64S. The grid-frame, grid-block, grid-container F4A and grid-row, grid-column on the F64S side.

I will try to come up with a grid-frame solution for F64S and make a PR in the end.

Thanks for all the good work you guys do btw. :)

**Comment by gakimball** [comment]
@Tschef Ah okay, from that perspective the fragmentation makes sense. That was a case where "row" and "column" didn't *quite* make sense for the Apps grid, because it's bigger on vertical grids, and carving up the screen into scrollable pieces and all that.

Here's how I would describe the difference:

![img_2510](https://cloud.githubusercontent.com/assets/1142001/11102978/a6ec0ab0-8874-11e5-9a74-523f64c686be.JPG)

In fact, I actually think Apps might need two grids: the app grid to make the "shell" of your design, and then a more normal 12-column grid that uses rows and columns and all that.

But that's a conversation for a few months from now, when we get back to Foundation for Apps ;)

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
