### ISSUE TITLE
[feature request] Turn Equalizer "data-equalizer-small-off data-equalizer-medium-on"

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites-6#220]
On medium/large screens it can be nice to use equalizer to align horizontal ordered elements.
On small screens I often order the elements below each other. Because of equalizer sometimes you get a lot of white space, as equalizer is still doing it's job. Like when the content inside the elements is not very equal in height.
There is no clear or easy way to turn equalizer ON for medium+large and to turn equalizer OFF for small.
Would be great though. Or is there and did I miss that?

Proposal how I think it could be easily implemented, see first line:
__data-equalizer-small-off data-equalizer-medium-on__
or maybe just:
__data-equalizer-medium__
so small sizes would not be equalized.
```html
<div class="row" data-equalizer-small-off data-equalizer-medium-on>
  <div class="small-12 medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <img src="http://placekitten.com/g/600/300" />
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <p>Pellentesque habitant morbi tristique senectus et netus et, ante.</p>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <div class="callout" data-equalizer-watch>
      <img src="http://placekitten.com/g/800/600" />
    </div>
  </div>
</div>
```

**Comment by rafibomb** [comment]
The default setting is equalizeOnStack: true, For now you can set this to false. We'd like to add this functionality. Something like - data-equalizer-mq="large-up" which is the syntax for 5. We have this on our roadmap for a future release so we'll close this here. Thanks!
