### ISSUE TITLE
Slider is not keyboard accessible

### ISSUE THREAD

**Issue by Wolfr** [zurb/foundation-sites-6#223]
The slider e.g. http://a42server.net/foundation/slider.html is not keyboard accessible.

See http://codepen.io/wolfr/pen/wKYMNP for an example of an accessible slider.

Was this a conscious choice? I know that the default HTML5 slider is hard to "enhance" but it can be done.

**Comment by Owlbertz** [comment]
There is actually code that makes Slider keyboard accessible. This works well on my machine in the local docs, but somehow not in the online docs, where no keyboard interaction is possible with any component. I will have a look why this is the case.
@Wolfr Did you run the docs on your machine and checked the behavior there?

**Comment by adamos42** [comment]
@Wolfr my code is a test for erasing junks, its not complete and not part of the foundation yet, in fact it does not load any of foundation javascript, but the keyboard access is nice thing to have, i will implement, also I will make the same features what the slider has on the documentation site.

**Comment by Owlbertz** [comment]
The keyboard support for Slider (and all other components) will be available with the PR #227. The regex I used initially just was not working with the minified JS.

**Comment by zurbchris** [comment]
This issue is resolved on the develop branch. Thanks for the feedback, and let us know if there's anything else we can improve!
