### ISSUE TITLE
Dropdown Menu sub menu off-screen for small viewports

### ISSUE THREAD

**Issue by Owlbertz** [zurb/foundation-sites-6#226]
When on mobile (e.g. 320px width) then the sub menus might start too far left so they are partly off-screen.
![dropdown-menu](https://cloud.githubusercontent.com/assets/4280373/11015107/7e7f9ffe-8551-11e5-9898-134f53d66bed.png)
I think there should be some sort of logic that prevents this behavior if the screen ins too small and instead renders the sub menu at the same spot as the parent.

**Comment by zurbrandon** [comment]
This looks pretty screwy in general, i feel like we could treat this as user error, since we're giving users the ability to convert  dropdowns on small screens to drilldowns or accordions. 

Thoughts?

**Comment by zurbchris** [comment]
That was the purpose of the ResponsiveMenu option, and there's nearly nothing that we can do to make a large dropdown like that look decent on a small screen. However, there is a change I can make to the JS for DDMenus that would at least overflow it to the right.

**Comment by Owlbertz** [comment]
While this might be a user error because of a wrong plugin choice, I think that the effort fixing this is rather low to make this a bit more failure tolerant. I can do that if @zurbchris is facing more important stuff at the moment.

**Comment by zurbchris** [comment]
fixed w/ #270
