### ISSUE TITLE
Feedback: Toggler plugin

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#23]
Toggler is a small JavaScript plugin that lets you set up a click trigger to add/remove a class on an element, without writing any JavaScript.

For us at ZURB, it solves a specific problem of wanting to prototype interactions in HTML only. **We'd like the community's feedback on if this seems like a useful plugin.**

```html
<!-- This is the element you're toggling a class on -->
<ul class="menu-bar" id="menuBar" data-toggler=".hide">
  <li><a href="#">One</a></li>
  <li><a href="#">Two</a></li>
  <li><a href="#">Three</a></li>
  <li><a href="#">Four</a></li>
</ul>

<!-- This is the click trigger that does it -->
<a data-toggle="menuBar">Show Menu Bar</a>
```

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
