### ISSUE TITLE
Documentation: [Installation] Clarification

### ISSUE THREAD

**Issue by carbinemonoxide** [zurb/foundation-sites-6#230]
In the command line tools section of the installation documentation for Foundation 6, the documentation instructs you to install foundation-cli using the following command:

npm install --global foundation-cli

Then to create a new project using the following command:

foundation new

This does not seem to work, and it turns out that this ends up installing foundation for apps. I was able to get this to work by using the following command to install foundation-cli:

npm install --global foundation-cli@beta

Once I've installed it this way, I am able to start using Foundation 6 for Sites.

**Comment by armsdev** [comment]
Exactly, what carbinemonoxide wrote, something goes not right.

```
PS C:\Users\Armando> npm install --global foundation-cli
npm WARN deprecated exec@0.1.4: deprecated in favor of builtin child_process.execFile
C:\Users\Armando\AppData\Roaming\npm\foundation-apps -> C:\Users\Armando\AppData\Roaming\npm\node_modules\foundation-cli\bin\cli.js

> foundation-cli@1.1.2 postinstall C:\Users\Armando\AppData\Roaming\npm\node_modules\foundation-cli
> node lib/welcome.js


           /|
          | |  /| .
     .  /\|  \/ |/|
     |\/          |         Thanks for installing Foundation for Apps!
     ||\__/\____/||         ------------------------------------------
  ___|| ======== ||___      Type foundation-apps new app to create a new app,
 /___||  O    O  ||___\     or foundation-apps help to see every command.
     ||  ______, ||
     /|          |\         We're @zurbfoundation on Twitter.
    /_/\\/\  /\//\_\
        \/\\//\/
           \/

foundation-cli@1.1.2 C:\Users\Armando\AppData\Roaming\npm\node_modules\foundation-cli
├── is-root@1.0.0
├── open@0.0.5
├── async@0.9.2
├── exec@0.1.4
├── colors@1.1.2
├── semver@4.3.6
├── nopt@3.0.4 (abbrev@1.0.7)
├── string-length@1.0.1 (strip-ansi@3.0.0)
├── which@1.2.0 (is-absolute@0.1.7)
├── npm@2.14.10
├── bower@1.6.5
├── rimraf@2.4.3 (glob@5.0.15)
└── update-notifier@0.2.2 (semver-diff@2.0.0, is-npm@1.0.0, chalk@0.5.1, latest-version@1.0.1, configstore@0.3.2)
```

**Comment by joepurdy** [comment]
@gakimball updated the docs to reflect using the beta version in commit b26e45b5c52193f243a072788b2e775387acac82

The website docs are still out of date though. This is fixed, just needs an update on the website.

**Comment by gakimball** [comment]
@carbinemonoxide @joepurdy We'll deploy a new version of the docs to the live site today that includes this change. Sorry for the confusion!
