### ISSUE TITLE
Docs Responsive Navigation drilldown to dropdown

### ISSUE THREAD

**Issue by armsdev** [zurb/foundation-sites-6#232]
Upon opening the page http://foundation.zurb.com/sites-6-docs/responsive-navigation.html
middle section with dropdown to drilldown menu shows really as dropdown. Then during re-sizing the broswer (Google Chrome) it changes to drilldown, but upon turning back to full size (~1080px) menu stays still as drilldown - not getting back to dropdown as on opener.

**Comment by zurbrandon** [comment]
Looks to be the case! Thanks, we'll take a look at it.

**Comment by zurbchris** [comment]
Should be resolved with: 14ec08a
