### ISSUE TITLE
Docs Kitchen Sink broken right-nav-magellan functionality

### ISSUE THREAD

**Issue by armsdev** [zurb/foundation-sites-6#236]
I don't know yet how to embed a video into this space, so I will just provide a link:

https://www.youtube.com/embed/HAHM_Jz7hbc

First of all, there is a kind of sub menu to the right, that is broken (revealed in first seconds of video). Probably it shouldn't appear on medium/large screens.

Then while scrolling down, highlighted items on Magellan aren't really showing the current, centered area.

Then while clicking each item in Magellan, whole screen kind of shakes and movement to the corresponding areas is not correct, content after clicking a link is not positioned well (appears on the bottom of the browser window). Seems like not everything is pinned correctly.

**Comment by zurbchris** [comment]
This should be resolved in the develop branch with 451c2bd.
