### ISSUE TITLE
topbar.scss settings not overridable

### ISSUE THREAD

**Issue by michael-wilson** [zurb/foundation-sites-6#237]
the variables defined in the _topbar.scss file are not marked as !default like they are in others (like _dropdown-menu.scss and others)

$topbar-padding: 0.5rem;
$topbar-background: #eee;
$topbar-link-color: #fff;
$topbar-input-width: 200px;

so cannot be overridden from the settings file as suggested in the docs. they should probably be.

**Comment by gakimball** [comment]
Fixed via b4414976d436fefda4bd964832e6f5a0b4a5085f
