### ISSUE TITLE
Foundation 6: no Css

### ISSUE THREAD

**Issue by saxs4x** [zurb/foundation-sites-6#244]
why there's no downloadable version of the beta release?
I can't wait to test it! Please!

**Comment by JeremyEnglert** [comment]
You can use the files from here: https://github.com/zurb/foundation-sites-6/tree/develop/dist

**Comment by gakimball** [comment]
What @JeremyEnglert said :) When 6 launches for realsies, we'll have all of the usual CSS downloads available.

**Comment by saxs4x** [comment]
Thank you very much!!

I'm going to have a lot of fun :)

:::Francesco Saccullo:::

Graphic, Art & Communication.

Ph: *3701130993*


2015-11-09 17:00 GMT+01:00 Jeremy Englert <notifications@github.com>:
