### ISSUE TITLE
Clearing in F6

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites-6#246]
Will there not be the clearing/lightbox functionality in foundation 6, as I did not see it in the docs?

**Comment by zurbrandon** [comment]
This will not be included by default, but will end up living in a separate repo. We found it was used on too small a percentage of projects to justify being a core component, but still recognize the need for it sometimes. We'll be recoding it after launch and ensuring it works within the framework.

**Comment by phifa** [comment]
that is too bad. The lightbox functionality is still THE way on all kinds of websites to show a bigger version of an image. If clearing will not be included, people will have to use lightbox, fancybox, etc. additionally to the framework. But they are all not as small as your plugin and well integrated. They come with all kinds of icons and stuff nobody needs. Maybe something else can be developed with MotionUi that makes it into the core? Anybody else using clearing? I fear, if it will not be included by default, it will get dropped eventually. IMHO things like joyride are way more optional than lightbox image zoom.

**Comment by octlabs** [comment]
Sorry, bit confused about the disappearance of Clearing. In F5 you announced EOL of Orbit - no word to RIP Clearing - F6 Orbit is still there!? Also can't find Clearing as F6 plugin :( 
I really liked and used it a lot.

**Comment by gakimball** [comment]
@octlabs Clearing, Joyride, and a new Datepicker plugin will be coming to the framework soon. We actually had a member of the community write a new, *much* slimmer Joyride for us already, so that one's already most of the way done.

**Comment by phifa** [comment]
yeah, really looking forward to it. Clearing seems just like must-have feature as it is on all kinds of websites the standard procedure to zoom in images. Is there a timeframe?

**Comment by gakimball** [comment]
@phifa We're going to publish a roadmap for Foundation 6 soon, which will have Clearing, along with a bunch of other features, on it.

**Comment by dpindrys** [comment]
*ahem*
