### ISSUE TITLE
Rem-calc function not working/available in _settings.scss

### ISSUE THREAD

**Issue by Mancherel** [zurb/foundation-sites-6#249]
I'm trying to override global-width in _settings.scss. The rendered css outputs max-width:rem-calc(800) instead of expected max-width:50rem

I can fix this by adding @import 'util/util'; in _settings.scss or before the import in app.scss. What is best practice? It's kind of confusing since this does not produce an error and I'm implied to use rem-calc on several locations in the settings file.

**Comment by colin-marshall** [comment]
Can confirm this issue. IMO this should be setup out of the box so that the `@import 'util/util'` and imports of any other functions that would be run in the settings variables come before the settings variables.

**Comment by zurbrandon** [comment]
Yeah, thats a bug. We'll be adding this in

**Comment by gakimball** [comment]
Opening an issue here to track this: zurb/octophant#2

**Comment by gakimball** [comment]
Updated the settings file with the import statements: 4dea008ef286cc026ea71e42142ae608cb7dd222

**Comment by colin-marshall** [comment]
@gakimball I updated the testing settings file to match your changes: https://github.com/zurb/foundation-sites-6/pull/253
