### ISSUE TITLE
Video modal should stop the video on close

### ISSUE THREAD

**Issue by adriantombu** [zurb/foundation-sites-6#250]
I'm just reading the doc for now, and I think that when you start a video on a modal, it should stop when you close the modal.
For now, it just keeps working in the background, I don't think users will like it ;-)

Seen in : http://foundation.zurb.com/sites-6-docs/reveal.html#video

**Comment by zurbrandon** [comment]
This is a thing pretty specific to Vimeo or Youtube, any idea on how we'd do that for all video?

**Comment by adriantombu** [comment]
Will, the only time I had to handle this, I resolved it with javascript. I saved the modal content in a data attribute before removing it from the DOM. 
I guess it's a bit dirty but it's the only working thing I found at that time.

**Comment by zurbrandon** [comment]
Ah so you saved the contents, destroyed them and then re-inject them? Was that pretty costly? I'm intrigued by it, but i wonder if it's just better to use the modals call back to then loop it in with your embed manually.

**Comment by zurbchris** [comment]
Unfortunately, there's no way to do that, (that I know of), with youtube videos without using the youtube api. They have their own JS library specifically for controlling content within your site.

**Comment by adriantombu** [comment]
@zurbrandon I will have a look at the callback this morning, that's the occasion to dive in Foundation as I'm new to it :)

**Comment by zurbchris** [comment]
I'm going to close this issue, thanks @adriantombu for the PR.

**Comment by adriantombu** [comment]
My pleasure :)
