### ISSUE TITLE
[Dropdown Menus] Submenu arrow position

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites-6#251]
In firefox or IE the indicator arrow on a submenu isn't in the correct position, its sitting a lot lower down.
This can be seen by looking at the docs, see below gif.

![dropdown submenu indicator](https://cloud.githubusercontent.com/assets/73229/11043957/1ef3a1da-8717-11e5-83be-d368a40f6167.gif)

**Comment by zurbrandon** [comment]
oh man, super odd visual bug. We'll have to look at whats doing that, unless you've already found the culprit.

**Comment by brettsmason** [comment]
I haven't found out what yet, its definately an odd one.

I did notice that the classes seem backwards to me: is-left-arrow is producing the arrow in the image above, shouldn't that be is-right-arrow?

Will see if I can find out the issue tomorrow.

**Comment by aibrean** [comment]
Are you looking at current Docs? I am and it looks fine. If you aren't running Docs locally then you probably should :) I noticed a bunch of errors that have been since fixed. It just hasn't been pushed to the F6 Site Docs page that's live.

**Comment by colin-marshall** [comment]
@aibrean are you looking at the local docs with Firefox? I have pulled all the recent commits, and am definitely seeing the problem in Firefox on Yosemite.

**Comment by brettsmason** [comment]
Possibly found the culprit though don't have time to check until tonight properly.
Line 46 of `_dropdown_menu.scss` has this: `white-space: nowrap;`

Removing this sorts out the issue in Firefox I think, though not sure if this impacts anything else yet.

**Comment by aibrean** [comment]
@colin-marshall I see it on Firefox. @brettsmason in inspector it doesn't affect Chrome to remove `nowrap`.
