### ISSUE TITLE
Motion UI / Built-in Transitions / Missing effects

### ISSUE THREAD

**Issue by armsdev** [zurb/foundation-sites-6#252]
```
foundation-sites@6.0.0-alpha.1
```

Seems like this element has missing a half of its functionality.
What's wrong, not working:
 <optgroup label="Slide">
      <option value="slide-in-down">slide-in-down</option> - not working at all
      <option value="slide-in-left">slide-in-left</option> - not working at all
      <option value="slide-in-up">slide-in-up</option> - not working at all
      <option value="slide-in-right">slide-in-right</option> - not working at all
      <option value="slide-out-down">slide-out-down</option> - works wrong, moves up instead of down
    </optgroup>
    <optgroup label="Fade">
      <option value="fade-in">fade-in</option> - not working at all (unless idk how it should looks like)
    </optgroup>
    <optgroup label="Hinge">
      <option value="hinge-in-from-top">hinge-in-from-top</option> - not working at all
      <option value="hinge-in-from-right">hinge-in-from-right</option> - not working at all
      <option value="hinge-in-from-bottom">hinge-in-from-bottom</option> - not working at all
      <option value="hinge-in-from-left">hinge-in-from-left</option> - not working at all
      <option value="hinge-in-from-middle-x">hinge-in-from-middle-x</option> - not working at all
      <option value="hinge-in-from-middle-y">hinge-in-from-middle-y</option> - not working at all
    </optgroup>
    <optgroup label="Scale">
      <option value="scale-in-up">scale-in-up</option> - not working at all
      <option value="scale-in-down">scale-in-down</option> - not working at all
    </optgroup>
    <optgroup label="Spin">
      <option value="spin-in">spin-in</option> - not working at all
      <option value="spin-in-ccw">spin-in-ccw</option> - not working at all
    </optgroup>
Here is a record of how it works like: https://www.youtube.com/embed/XuiFD7wV_18

**Comment by gakimball** [comment]
Fixed via 6f0a0a9aad280a253b53808157f3f19ec5030613

Turned out to be a problem with the demo code, not Motion UI itself.
