### ISSUE TITLE
Dropdown Menu Arrow Moves Below Text on Small

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#254]
![screen shot 2015-11-09 at 9 28 42 pm](https://cloud.githubusercontent.com/assets/6110968/11054395/f3af1038-8728-11e5-9316-0aa933a1d8e8.png)

**Comment by zurbrandon** [comment]
Yeah, just noticed this mu self. We'll jam on a fix for it soon, unless you have pinpointed it and would like to do a PR.

**Comment by JeremyEnglert** [comment]
I've found a couple ways to address it, but I'm not sure if either is the best approach.

Setting the :after element to absolute positioning and then adjusting top/right settings allows the positioning to stay in place. It would also be easy to setup variables to adjust these positions - allowing users to have more control over the arrow positioning.

Another fix would be to change the display of .menu > li > a to flex (currently it is block).

**Comment by RedLucas** [comment]
I think the absolute positioning with top/right is probably the best option for now... Unfortunately. I'd be happy to write that out if everyone else agrees with it.

**Comment by gakimball** [comment]
@JeremyEnglert @RedLucas That was the 11th-hour change we made before the framework shipped. Extra padding on the right and the arrow is absolutely-positioned.
