### ISSUE TITLE
Adapt Foundation to a custom folder structure

### ISSUE THREAD

**Issue by megakoresh** [zurb/foundation-sites-6#255]
Hey, I was wondering if that is reasonably easy to do. That has been a hassle for the previous version. I use Sails.js for my projects, which uses Grunt in turn for asset management and all of it's frontend is located in the `projectroot\assets` folder. There, for example, `styles` folder typically holds all the source style files (like scss, less, etc) and then `js` folder has `dependencies` which is loaded before other javascript and so on. When the server starts all that is compiled to `.tmp` folder. 

What I did for the previous Foundation version is I modified existing Grunt configuration inside Sails project to compile Foundation's scss and javascript into the `.tmp` directory. However the new version compilation seems to be more complicated with prefixing being it's separate task, for example, and UnCSS and so on. And on top of that it uses Gulp, not Grunt. So I was wondering about adaptability. Is there some sort of guide on how the tasks are performed and in what order, so one can modify the deployment process to suite their needs or some kind of port to Grunt.

**Comment by zurbrandon** [comment]
Yeah, between the 2 templates, you should be able to modify the basic stack pretty easily. 

https://github.com/zurb/foundation-sites-template

The advaced stack has uncss and such, but we keep this one, to make modification easier on a per project basis.

**Comment by megakoresh** [comment]
Hmm, that doesn't take care of the Javascript concatenation and `_settings.scss` file generation and motion-ui, which are all quite important features of foundation, aren't they? In fact I am not exactly sure how to use that basic template. Seems like this is something that would be useful to add to documentation. A lot of people use MVC frameworks on the backend these days, I am sure this is a common use case. Right now I am trying to port your gulp tasks to grunt with my projects server structure. It is not actually working, for some reason, that I haven't figured out yet.

**Comment by gakimball** [comment]
@megakoresh You'll want to take a look at [foundation-ssg](https://github.com/zurb/foundation-ssg), which covers the more advanced stuff you're talking about. It does:

- Handlebars templates
- Sass to CSS (with Autoprefixer, CleanCSS and UnCSS)
- JavaScript concatenation and UglifyJS
- Image compression
- Source maps
- BrowserSync

Both templates were also just updated to include Motion UI out of the box. As for the settings file, eventually we'll get to a place where one can be generated on the fly every time you download a fresh project, but it's not there yet.

If you get any specific Sass or JS errors when implementing our code into your own build process, could you let us know in a new issue? Thanks. :)

**Comment by megakoresh** [comment]
That will do nicely, thanks! Maybe include that link docs so it's easy to find?

**Comment by gakimball** [comment]
We have a page that breaks it down: http://foundation.zurb.com/sites-6-docs/starter-projects.html#advanced-project

Although this is about a week or so out of date with the current documentation.
