### ISSUE TITLE
Foundation 6 installation kills Foundation 5 without warning

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites-6#261]
I had a fantastic idea, maybe someone would like to contact me to make a multi-million dollar startup out of it: just imagine you could use Foundation 5 *and* Foundation 6 both at the same time in your working environment? Wouldn't that be revolutionary? Wouldn't that change *everything*? *Nobody* ever thought about this before, especially not the creators of Foundation.

Well, it seems like this project is not designed for environments with multiple versions of Foundation installed. Now I am asking myself "Who is *not* using foundation 5 *and* foundation 6 for beta testing?" 

After naively following the installation instructions published [here] (http://foundation.zurb.com/sites-6-docs/installation.html) I have only the ```foundation``` command of version 6 in the environment. Foundation 5 is not available any more and I need to spend the afternoon with yak-shaving to rebuild the frontend workflow (it is not my main job to maintain the frontend tools, so please excuse my slightly snarky tone - I feel much better now. Thank you.)

It would be very sympathetic, forsightful and generally sagacious, if there was some information provided in the install docs how *not* to f* up our work environment and how to create a working environment with foundation 5 *and* 6 - yes *both at the same time* - just imagine! 

At least please put some warning in the install docs: 

Attention: this installation of Foundation 6 comes with a nice time-burner for people who are extremely bored and have absolutely no ideas about what to do right now. If you feel like this, then go on! If you do *not*, then please note: this install procedure of Foundation 6 will overwrite your Foundation 5 tools! if you wanted to spend the afternoon with your friends to enjoy the beautiful colors of fall, please do not install this beta right now, as it will destroy everything F5 related.

As a special incentive we did *not* provide *any* information about how to rollback or how to install *both* versions of Foundation - this makes you spend even more time with an annoying breakage of your "frontend tools pipeline" and you can spend the whole afternoon with the gory details of the brilliantly designed node packaging infrastructure - real fun for people without a life, a warm welcome to our beta test! Expect more fun with Foundation 6!

:)

**Comment by aibrean** [comment]
Well F6 doesn't have the same naming conventions globally and a lot has changed.

The first thing I did was make myself a cheat-sheet of changes:

1. Flex Grid (new)
 - Advanced Sizing
 - Responsive Adjustments
 - Automatic Stacking
 - Horizontal Alignment
 - Vertical Alignment
 - Equal Height
 - Source Ordering
2. Block Grids 
 - now part of the main grid system
 - use [size]-up-[n] (small-up-2)
3. Float naming convention
 - Instead of left/right it’s now float-left, float-right, and float-center (center is a hack)
4. Accordions
 - Now show open/close state icons
 - Multi-expand functionality
5. Menu
 - Pretty substantial overhaul to be much more semantic.
6. Off-canvas
 - More like Foundation for Apps and not as tied into the menu system
7. Thumbnail class
 - now is “thumbnail” rather than “th”

**Comment by gakimball** [comment]
It's very easy to get the Foundation 5 CLI back. It hasn't disappeared; you just have two `foundation` commands now, and with the way your Bash path is configured, the new Node one wins over the old Ruby one.

To get it back, run `npm uninstall foundation-cli --global`. I added a callout to the docs explaining this: 420a7d2de30cdbfae081759cd992cf997272ccb4

We don't have plans for compatibility between the 6 and 5 CLIs. It's worth noting, however, that it doesn't affect your existing projects at all. The CLI only scaffolds new projects; your existing projects will still work with `compass watch` and `grunt`.

Lastly, I understand you're frustrated, but in the future could you tone down the snark in your issues? It's much easier for us to help you with the problem you're having if you're more direct with us.

**Comment by COLABORATI** [comment]
I just needed some humor, please do not take it personally, just build some distance to it and laugh about it - it is not meant as an attack. But please also design your tools in a way that it is possible to use both versions at the same time without major fiddling. The tools do not need to be compatible, but it should be possible to use F5 and F6 side by side, as it is clear that both versions of the framework will be used for some time. Thanks for your attention and have a nice day! :heart:

**Comment by gakimball** [comment]
@COLABORATI Don't worry, it didn't offend us :) We know these tools are vital to developers and designers, and always appreciate feedback.
