### ISSUE TITLE
when building with --production, GULP/UNCSS error comes up.

### ISSUE THREAD

**Issue by alanontheweb** [zurb/foundation-sites-6#263]
I'm on the default build. Haven't touched anything yet, and I can run gulp and see that everything works fine. When I add the --production flag to it, Gulp starts compiling and it errors out at:

/Users/username/Documents/Projects/design-7/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
Error: uncss/node_modules/css: unable to parse undefined:
property missing ':' near line 1:24346
	1:     -> ground-image:url("data:image/png;base64,
	2:        

    at error (/Users/username/Documents/Projects/design-7/node_modules/css-parse/index.js:57:15)
    at declaration (/Users/username/Documents/Projects/design-7/node_modules/css-parse/index.js:189:33)

Thoughts? I'm on Gulp 3.9, Node 4.1.1 and NPM 3.3.4

**Comment by zurbrandon** [comment]
I'll see if @gakimball can take a look, this may have already been fixed on one of the templates.

**Comment by gakimball** [comment]
I just made a bunch of refinements to the Gulpfile, see if it works for you now.

**Comment by gakimball** [comment]
Foundation 6 development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). Now that the ZURB Template's structure has been finalized, if you have any more problems, let us know in a new issue on that repo. Thanks!
