### ISSUE TITLE
Off Canvas Menu Items positioning problems

### ISSUE THREAD

**Issue by yogiderek** [zurb/foundation-sites-6#264]
I created a test site using Foundation CLI version 2.0.0-beta.2 and the advanced template, to become familiar with F6, and edited the body of default.html as shown below. Nothing else has been changed. When the off canvas menu is opened, the first menu command does not sit beneath the close button. Also the default colour of the close button X is the same as the hover colour. If you press F12 for the diagnostic tools, the X picks up the correct default colour and if you press F12 again it returns to the hover colour. I have tried to investigate but cannot find the issue. There are no errors in the console window either when the site is opened or the menu icon is clicked. To see the problem in real life visit      http://f6-beartree.rhcloud.com/

```html
<body>
<div class="off-canvas position-right" id="offCanvas" data-off-canvas data-position="right">
    <button class="close-button" aria-label="Close menu" type="button" data-close>
        <span aria-hidden="true">&times;</span>
    </button>
    <ul class="menu vertical">
        <li><a href="#">One</a></li>
        <li><a href="#">Two</a></li>
        <li><a href="#">Three</a></li>
        <li><a href="#">Four</a></li>
        <li><a href="#">Five</a></li>
        <li><a href="#">Six</a></li>
    </ul>
</div>

<div class="main-content" data-off-canvas-content>
    <div class="title-bar">
        <div class="title-bar-left">
            <span class="title-bar-title">F6 Test Site</span>
        </div>
        <div class="title-bar-right">
            <button class="menu-icon" type="button" data-open="offCanvas"></button>
        </div>
    </div>

    {{> body}}

</div>
<script src="./assets/js/app.js"></script>
</body>
```

**Comment by zurbrandon** [comment]
Yeah, we actually just pushed a big update to the develop branch that will solve the off-canvas woes. I'll close this, since it seems like it will fix your issue. 

Thanks for reporting!

**Comment by aibrean** [comment]
```scss
.off-canvas-wrapper-inner.is-off-canvas-open {
   overflow-y: hidden; 
}
```

overflow-y seems to be hiding the off-canvas menu when I did a git pull.
