### ISSUE TITLE
Sizing for input field

### ISSUE THREAD

**Issue by muhammadcahya** [zurb/foundation-sites-6#265]
I think like sizing in button, tiny, small, basic, or large. input fields must also have the option to size. What is your opinion ?

**Comment by zurbrandon** [comment]
We didn't think they'd be as widely used, so weren't worth the file size. Once you take in all the different types of inputs and how they are used in different components, it can really add up.

**Comment by zurbrandon** [comment]
We chatted about it and don;t think this is as much of a necessity as we'd want, for adding into the CSS. I'll close this. 

Thnamks for the discussions though, it's always good to bring it up incase its an oversight.
