### ISSUE TITLE
Full Reveal Modal unexpected behavior

### ISSUE THREAD

**Issue by getup8** [zurb/foundation-sites-6#267]
At least in the documentation example, the full screen modal does not seem to close upon hitting `esc` (which I think it's supposed to do).  It also closes when you click anywhere in the modal, not just the close button.

http://foundation.zurb.com/sites-6-docs/reveal.html#full-screen

**Comment by zurbrandon** [comment]
Yep, looks like a bug! I'll mark it for now, but if you know JS feel free to throw a PR our way. 

Thanks!

**Comment by Owlbertz** [comment]
This seems to be related to #223 and caused by the minified version of the JS. This should be fixed already in the dev branch by @zurbchris I believe.

**Comment by zurbchris** [comment]
This issue has been resolved on the dev branch, let us know if you still have issues with Reveal. Thanks for your feedback!
