### ISSUE TITLE
Should Motion-UI be included by default?

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#268]
Components such as Orbit rely on Motion-UI to work, so should Motion-UI be included by default?

I spent a good amount of time trying to figure out why Orbit wasn't working before I realized Motion-UI needed to be imported separately.

Or maybe a callout in the docs stating that Motion-UI is required for Orbit?

**Comment by zurbrandon** [comment]
Yeah, this is something we've been wondering. Ideally all these plugins should have defaults if motion ui ins't included, but i'll mark this as a bug for now.

**Comment by zurbrandon** [comment]
Got this added by default. Thanks!
