### ISSUE TITLE
Flex column align with sass?

### ISSUE THREAD

**Issue by sashafokin** [zurb/foundation-sites-6#274]
Hello! I got a promblem with flex colum alignment. Now i trying to use Foundation 6 with new feature called Flex Grid.

I sure, that is a great thing, but i need help. I want to use custom CSS classes:

.custom{@include flex-grid-column(6);}

And also i need keep it middle. I tried to use some combinations like:
.custom{@include flex-grid-column(6); @extend .align-middle;}
.custom{@include flex-grid-column(6); @include align-middle;}
etc...

But anything not working and returns erorrs. Please, help me. How i can use these classes in my custom classes? In new docs nothing said about alignment in custom classes.

**Comment by zurbrandon** [comment]
Yeah, these should be mixins, or atleast parameters of mixins, I'll label this as a bug and see how we can get that updated.

**Comment by sashafokin** [comment]
Yea, thank you for your fast answer. Hope your team fix this soon.
So now i can use this new feature by adding align class to my custom classes in HTML, not CSS?
Waiting for updates:)

**Comment by gakimball** [comment]
Reopened at zurb/foundation-sites#7106
