### ISSUE TITLE
Can't specify $grid-column-gutter on settings in flex-grid

### ISSUE THREAD

**Issue by rspt** [zurb/foundation-sites-6#275]
Hello,

I've got a problem trying to override (in settings.css) the `$grid-column-gutter`. The gutter didn't change at all.

Thanks

**Comment by gakimball** [comment]
In my testing, this appears to have been resolved in the final release of Foundation 6.

We've moved development back to the main Foundation repo: [zurb/foundation-sites](https://github.com/zurb/foundation-sites). If you run into any more problems with the framework, open a new issue there. Thanks! :)

**Comment by rspt** [comment]
Yes for sure!

Thanks for the answer!
