### ISSUE TITLE
[Drilldown Menu] Nested drilldowns show parent levels underneath

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites-6#283]
**How can we reproduce this bug?**

Make a list that is longer than the nested drilldown. 

**What did you expect to happen?**
An experience similar to F5 where in the drilldown, the canvas is shifted (i.e. the parent is hidden from view while the drilldown is expanded).

**What happened instead?**

You'll notice that the nested does cover up the parent, but the height doesn't change to cover up the parent so you can see it underneath (which is how I am assuming this is handled now). This proves especially problematic on 3-deep levels.

**Test case**
http://jsfiddle.net/aibrean/t4749a1m
(this uses the style from the F6 documentation)

**Comment by zurbrandon** [comment]
@zurbchris Maybe we can fade opacity as they slide and then add display none, so the click events don;t register? Any problem with this on how it's set up?

**Comment by zurbchris** [comment]
This is a pita because of the unified menu structure, but I'm on it.

**Comment by zurbchris** [comment]
Resolved by #300
