### ISSUE TITLE
[Top Bar] Title appears only on dropdown menu items

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites-6#284]
**How can we reproduce this bug?**

Use the topbar, then hover over a dropdown menu and you will see the title, but not on menu items without a dropdown. The title is being dynamically generated by the js.

**What did you expect to happen?**

I prefer no titles on menu items so if they are required in some level, they can be added in the markup.

**Test case**
http://foundation.zurb.com/sites-6-docs/top-bar.html#basics 
The topbar example replicates the issue.

**Comment by gakimball** [comment]
We're not sure what you're referring to here, as dropdown menu items don't have titles. (Assuming you're referring to the `title` attribute.) Might have been something an older version of the plugin did, though.

This repo is being shut down soon, as development has moved back to the main Foundation repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). If you're seeing the same issue with the live 6.0.3 release, or if you see anything else, open a new issue there and let us know. Thanks!
