### ISSUE TITLE
Does Panini support sub folder source / dist structure?

### ISSUE THREAD

**Issue by 4shoda** [zurb/foundation-sites-6#285]
I am responsible for a website that has several hundred pages. In order to manage those page more effectively, a sub folder structure has been in place which we would like to maintain. 

I'd love to use Foundation 6 site building partials and pages for this website. In order to do so, I would need it to support sub folders.  I have not been able to test this yet as I haven't been able to get Foundation 6 correctly configured on my Windows machine. 

The way I envision it would work would be to support a subfolder structure in the \src\pages folder which would then be replicated in the \dist folder. For example, I might have:

           \src\pages\support\supportpage1.html
                                          \supportpage2.html
           \src\pages\education\learnpage1.html
                                             \learnpage2.html

And it would generate: 

           \dist\support\supportpage1.html
                               \supportpage2.html
           \dist\education\learnpage1.html
                                   \learnpage2.html

I don't care if they all use same partials folder. Does this work? Or is there another way to enforce a subfolder structure (other then telling me to remember what goes where!!!)

Oh and to make it even more complicated, we actually have sub folders of sub folders right now.

**Comment by zurbchris** [comment]
Not yet, but we're working on it.

**Comment by 4shoda** [comment]
That's a great answer. Thanks!
