### ISSUE TITLE
Uncommenting _settings.scss results in error because of alphabetical ordering

### ISSUE THREAD

**Issue by danielck** [zurb/foundation-sites-6#289]
As they are now, the settings in `_settings.scss` do not work without editing variable values or changing the order of the various sections. They are ordered now in alphabetical order, which results in eg. Global settings being halfway down the file, even though many preceding sections are dependent on variables such as `$global-margin`, `$primary-color` etc. Another example: the Joyride settings rely on `$tooltip-*` variables, which are at the very end of the file.

I'm happy to try and find a working order manually and submit a PR, but perhaps there is a better, automated way of doing this?

**Comment by gakimball** [comment]
We've made two changes to the settings file to address this:

- Global sections come first now.
- All variables are uncommented, to prevent Sass errors around variables not yet being defined.

See: 6a29585459675b532be3b3594532188e8ea49f52
