### ISSUE TITLE
using bower install --save package in advanced layout

### ISSUE THREAD

**Issue by awojtczyk** [zurb/foundation-sites-6#290]
Hi there!
How i should include for example owlcarousel after installing it via bower?

Should i include it in gulpfile (sasstask), or directly in .html layout?
Would someone guide me please?

**Comment by gakimball** [comment]
Near the top of your project's Gulpfile is an array that defines various asset paths. You can add new paths to `assets.sass` for Sass libraries, or `assets.javascript` for JavaScript libraries.

```js
var PATHS = {
  assets: [
    'src/assets/**/*',
    '!src/assets/{!img,js,scss}/**/*'
  ],
  sass: [
    'bower_components/foundation-sites/scss',
    'bower_components/motion-ui/src/'
  ],
  javascript: [
    'bower_components/jquery/dist/jquery.js',
    'bower_components/what-input/what-input.js',
    'bower_components/foundation-sites/dist/foundation.js',
    'src/assets/js/**/*.js',
    'src/assets/js/app.js'
  ]
};
```
