### ISSUE TITLE
Dropdown Background Colour

### ISSUE THREAD

**Issue by RedLucas** [zurb/foundation-sites-6#293]
The foundation 6 documentation suggests an issue regarding the dropdown needing a background colour.

**Comment by RedLucas** [comment]
I went ahead and tried to resolve what I believe was the problem and changed the dropdown to a variable. I forked and created a pull request at https://github.com/advisorwebsites/foundation-sites-6/pull/1

**Comment by zurbrandon** [comment]
Yeah, we'll need to add this! We also are talking about potentially needing a border or shadow, so we may just add those in one swoop.

**Comment by zurbrandon** [comment]
Went ahead and added this to the develop branch, while i was in adding the border.

Thanks!
