### ISSUE TITLE
Should What-Input be treated as a vendor file?

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites-6#295]
Will What-Input be included by default or should be be treated as a vendor file? 

I fear that if the implementation isn't extremely straight forward/easy, people will simply revert back to outline:none.

**Comment by zurbchris** [comment]
It's a single `@include` per plugin/mixin, doesn't get much simpler.

**Comment by JeremyEnglert** [comment]
@zurbchris, I get that. My question was more about the implementation/installation of What-Input, mainly the JS.

Will what-input be included as a vendor file (like jQuery and Modernizer) or will it be bundled into the core JS?

**Comment by JeremyEnglert** [comment]
I see this will be included with NPM. That answers my question. Closing.
