### ISSUE TITLE
[Reveal] Issue Name

### ISSUE THREAD

**Issue by amagdic** [zurb/foundation-sites-6#299]
**How can we reproduce this bug?**

1. Step one
if you go to modals
2. Step two
open any of them in new FF
3. Step three

**What did you expect to happen?**
modal, but without scroller
**What happened instead?**
disabled scroller is shown

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by zurbchris** [comment]
This should be fixed now, based on my testing over the weekend. Reopen if you still have this issue. Thanks!
