### ISSUE TITLE
Tabs deeplinking

### ISSUE THREAD

**Issue by apcrane** [zurb/foundation-sites-6#304]
Hi, I'm trying to select a tab based on a hash value at the end of the URL, however this either doesn't appear to be an option or isn't currently doable without writing my own JS to handle this. Also, isn't this what the deeplinking option is?

I have also tried calling:

 Foundation.Tabs._handleTabChange() passing in the element that I want to select i.e. $('#panel3')

**Comment by zurbchris** [comment]
Deeplinking isn't yet implemented. I do concur there should be a public function to change tabs, I'll get that built and in the dev branch within the next day or so.

**Comment by zurbchris** [comment]
Public function now exists. Deeplinking will likely be a near-future feature, it's on the list, just not currently included. 
Function is `selectTab` and can take a string of the id or jQuery element representing the content pane you wish to display. 004de25

**Comment by apcrane** [comment]
Hi, thanks for looking into this, However I am getting an undefined on $tabTitles on line 223:

 var $target = this.**$tabTitles**.find('[href="' + idStr + '"]').parent('.' + this.options.linkClass);

I have tried passing in the element and the string of the panel id, i.e.:

Foundation.Tabs.prototype.selectTab($('#panel3'));
Foundation.Tabs.prototype.selectTab('#panel');

**Comment by zurbchris** [comment]
The *easy* way currently available to do this is to call the function on the `tabs` object directly.
```js
Foundation._activePlugins[$('#exampleTabsSelector').data('tabs')].selectTab('#panelToSelect');
```
I'll be writing a function to make it even simpler in the future. But, for now, this is the easiest way to do what you want.

**Comment by zurbchris** [comment]
New method added, calling `.foundation('method', 'arg1', 'arg2'...)` on a valid jQuery element will invoke a function on a single plugin or a collection of plugins.
example:
```js
$('[data-tabs]').eq(0).foundation('selectTab', $('#panel4'));
// Will open the selected panel on the first Tabs element on the page
```
or
```js
$('[data-tooltip]').foundation('destroy');
// Will destroy all Tooltips on the page
```
The method returns the jQuery collection, so you can chain this as well.

```js
$('#mrMeeseeks').foundation('open').addClass('look-at-me');
```

**Comment by apcrane** [comment]
Many thanks for creating that functionality, that is all now working for me. 

I look forward to the deeplinking working, but for now I can create my own JS function to handle this.

**Comment by apcrane** [comment]
One thing I have noticed, I just pulled down the latest code and whilst the first tab is selected, the panel isn't being displayed.

**Comment by zurbchris** [comment]
That's super weird, I didn't change how the tabs display.

**Comment by zurbchris** [comment]
I'm not able to reproduce this, do you have an example hosted somewhere by
chance?

**Comment by apcrane** [comment]
I realised how I managed to do this, basically I had the ‘is-active’ class on the li.tabs-title element but not on the tabs-panel that I wanted to be active.
