### ISSUE TITLE
modernizr not installed

### ISSUE THREAD

**Issue by guyvanbael** [zurb/foundation-sites-6#305]
Using npm. Modernizr is not included after installing.
 <script src="bower_components/modernizr/modernizr.js"></script>

**Comment by zurbchris** [comment]
Modernizr is not a dependency of Foundation 6.

**Comment by guyvanbael** [comment]
Hey Chris,

In the index.html that is created however there is a link to modernizr. In
Foundation 5 modernizr was automatically added.
What is best practice to add modernizr then?

Thanks for helping out! Keep up the good work. Foundation is awesome!

2015-11-16 18:29 GMT+01:00 Chris Oyler <notifications@github.com>:
