### ISSUE TITLE
Docs or tools to migrate from F5 to F6

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites-6#307]
Any specific documentation on how to migrate a Foundation 5 project to Foundation 6 would be great. Ways to refactor code, new technique, etc. A TL;DR section, basically.

Any tools to help migrate? I've been using Codekit for awhile, should I use something else? 

Anxiously awaiting public release.

**Comment by zurbchris** [comment]
Migration guide will be included with launch.

**Comment by dlewand691** [comment]
Great! Can't wait. Thanks for all the hard work!
