### ISSUE TITLE
Split buttons - Not equal height

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#310]
It looks fine on the foundation docs

I'm using

cd foundation-sites-6
npm install
npm start
Which I ran about an hour ago.

I am using the dist css

The split buttons are not equal height like the docs show.

I'm using el capitan mac, all up to date browsers - firefox, safari and opera. They all look uneven as per button split test.png

I'm creating my own kitchen sink -- 
![button split - foundation docs](https://cloud.githubusercontent.com/assets/14908417/11198734/a3fe7b80-8c84-11e5-86da-069e57dbec94.png)

P.S. how do I add a label to this post.

![button split - test](https://cloud.githubusercontent.com/assets/14908417/11198735/a85e8df0-8c84-11e5-9d91-fc58868be619.png)

**Comment by colin-marshall** [comment]
Have you pulled the latest changes? This was supposedly fixed already: https://github.com/zurb/foundation-sites-6/issues/173

**Comment by blynnc** [comment]
I used

cd foundation-sites-6
npm install
npm start
Which I ran about 16 hours ago..
using the dist css

I'll try again and let you know later

**Comment by gakimball** [comment]
@blynnc The dist CSS was out of date by about a week, so I went ahead and generated new files.

But yes, this issue has been resolved.
