### ISSUE TITLE
Docs Left Bar (Current Page Hilite)  and Docs Labels Icons Confusing

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#311]
First In General.

1 - DOCS. There is no current page highlight - I have no idea when looking at docs left nav bar
Joke:  I go to have a glass of pre - dinner glass of wine  and come back. WHERE THE H-LL am I ???
This has nothing to do with my glass of wine ; ). 

2 -  DOCS > LABEL
With Icons
An icon can be dropped into a label just fine.

Oh yeah ?   I think instructions need to be included on what needs to be added to the head to get these icons to show up.

**Comment by blynnc** [comment]
See attached image - I'm on sticky page in docs somewhere towards bottom. Would be very helpful if there was current page hilite on the left nav - for immediate visual confirmation.

Looking at the attachment - if I did not say sticky page - you would  not know what page I am on.
![sticky page - no current page hilite left nav](https://cloud.githubusercontent.com/assets/14908417/11217156/244458b4-8d0c-11e5-9be4-8a9040b33fd7.png)

**Comment by gakimball** [comment]
Added an active state to the docs with [this commit](0e7e7256a4851dc8f846dbc14e7bcb0c67efdb45).

Updated the label and badge docs to clarify where the icons come from with [this commit](b6a36f3ea5e0ee70874aaed2dfe252bb829d0a45).

We'll get a deploy out with these changes this week. Thanks for the suggestions! :)
