### ISSUE TITLE
.foundation-mq style in different file

### ISSUE THREAD

**Issue by mexn** [zurb/foundation-sites-6#315]
In order to get clean custom sass builds,
it would be pretty neat, if the
`.foundation-mq` style definition would not be in the root sass file, but instead in a e.g. `util/_breakpoint.scss` or wherever it fits most.
So I do not have to copy it into my own root.

**Comment by gakimball** [comment]
Implemented with [this commit](https://github.com/zurb/foundation-sites/commit/c3801a39bd7b9aa4613d11385bd04febb5e77730).
