### ISSUE TITLE
Windows -  Gulp Throw Error 

### ISSUE THREAD

**Issue by 4shoda** [zurb/foundation-sites-6#316]
I'm trying to get Foundation 6 installed on one of my Windows computers. I have tried it on both my laptop running Windows 10 and my desktop running Windows 7 because I thought maybe there was an issue with Windows 10. Both computers get stuck in the same place - a throw err when running Gulp. 

I have installed git, ruby, installed node (4.2.1), gulp, grunt, MinGW (GCC files that I guessed where the ones referenced but I wasn't sure as MinGW pulled up a lot of stuff). Maybe I didn't grab the correct things? But I do have Visual Studio installed which was supposed to take care of compiler dependencies. I also verified that ruby is working, and that the paths are set up correctly for nodejs and bower works. 

I was not sure if I need to install Gulp globally and in project dependencies file. Don't remember if I did that or not. 

My last attempt was to clone the git dev version of Foundation 6 as I assumed the directions should point me the way to a working version of Foundation 6. That version was from about 11 days ago. Gave me the same error as I had on my own version. 

Here is the error I am getting. (log file information follows) 
---------------------------------------

"C:\Program Files (x86)\JetBrains\WebStorm 143.379.15\bin\runnerw.exe" "C:\Program Files (x86)\nodejs\node.exe" gulpfile.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'panini'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (g:\BT Webs\+ F6\Buzz_Foundation6\gulpfile.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

Process finished with exit code 1
----------------------------------------------

Log File contains: 

 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart foundation-sites@6.0.0-alpha.2
6 info start foundation-sites@6.0.0-alpha.2
7 verbose unsafe-perm in lifecycle true
8 info foundation-sites@6.0.0-alpha.2 Failed to exec start script
9 verbose stack Error: foundation-sites@6.0.0-alpha.2 start: `gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid foundation-sites@6.0.0-alpha.2
11 verbose cwd G:\BT Webs\+ F6\test\foundation-sites-6
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error foundation-sites@6.0.0-alpha.2 start: `gulp`
17 error Exit status 1
18 error Failed at the foundation-sites@6.0.0-alpha.2 start script 'gulp'.
18 error This is most likely a problem with the foundation-sites package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp
18 error You can get their info via:
18 error     npm owner ls foundation-sites
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
------------------

Hopefully someone can help me get this set up correctly? Anyone recognize what the issue is?

**Comment by zurbchris** [comment]
What version of NPM are you on?

**Comment by 4shoda** [comment]
NPM is at 2.14.7

**Comment by zurbchris** [comment]
Hmm. Did `npm install` finish without any errors? If not or you're not sure maybe try: 
```bash
$ /foundation-sites-6: rm -rf node_modules
$ /foundation-sites-6: npm install
$ /foundation-sites-6: npm start
```

**Comment by 4shoda** [comment]
Ok now this is weird. the rm command did nothing but I went ahead and did your second suggestion anyways. First time I did the npm install it threw a bunch of errors and scrolled the screen for pages and pages. I didn't capture them - sorry. But I tried the npm install a second time and it seemed to work. Huh? I just love intermittent errors. 

Then I did the npm start and again - it seemed to finish correctly. 

I then went to Webstorm and ran gulp and it finished with an exit code of 0. I'm going to play with it a bit more to see if I can make some changes and have it run.

I'm also going to try this on my laptop - maybe I can write down a few of the errors. It seems odd that there would be errors and then not but heck - it's windows. Once I do a bit more testing I'll close this. 

Thanks for your help!

**Comment by 4shoda** [comment]
Ok, I went to my other foundation folder - the one with the cloned Foundation 6 (I had two) and again I got a similar error except this time it was an error that said it could not find the gulp-util. So I went to the node modules folder and there wasn't that module listed. Once I installed it using npm, the error went away and I was finally able to complete the gulp on the cloned project. It even created the files in the dist folder so I think it was a combination of things. 

I'm going to try to document the little details I needed to get it running and see if I can get it going on my laptop where I had a similar issue. I'd like to have a simple check list for this with what to install (and where) and how to check what was installed before going onto the next step. 

Thanks so much for your help! I'm excited to start playing with it "for real"

**Comment by gakimball** [comment]
FYI we've moved development back to the original repo, which was renamed [foundation-sites](https://github.com/zurb/foundation-sites). You'll want to download that new repo when you have time. The `master` branch is for the most recent stable version (6.0.1 at the moment), and `develop` has all of the latest changes.
