### ISSUE TITLE
Unit tests location for new components

### ISSUE THREAD

**Issue by dragthor** [zurb/foundation-sites-6#32]
Where do you guys want unit tests for the new components?  Maybe we put the old tests under `spec/foundation` and the new tests under `spec`?  This is similar to the `js` directory.

**Comment by gakimball** [comment]
We pulled in #200 a while back to stub out a testing environment with Mocha and Chai. Although we still haven't *written* any tests yet ;) Follow our unit testing adventure at [Foundation 6's permanent home](https://github.com/zurb/foundation-sites).
