### ISSUE TITLE
aria-expanded doesn't change on accordion menus

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#322]
To recreate, open the docs and click open and closed accordion menu items. The value of the `aria-expanded` and `aria-selected` attributes on the `<li>`s doesn't change.

**Comment by brettsmason** [comment]
This was marked as fixed on an issue I raised before: [204](https://github.com/zurb/foundation-sites-6/issues/204) - maybe that will help with fixing it?
