### ISSUE TITLE
Certain tab settings don't take affect.

### ISSUE THREAD

**Issue by halfbakedsneed** [zurb/foundation-sites-6#324]
Hi! Changing the following settings in _settings.scss has no effect on the tab component:

<pre>
<code>
$tab-background
$tab-background-active
$tab-item-color
$tab-content-color
$tab-item-background-hover
</code>
</pre>

For the first four of these variables, i think the problem is that the <code>!default</code> flag is omitted from the variable declarations in the _tabs.scss component file. The last variable just isn't used at all in the component sass.

**Comment by gakimball** [comment]
Fixed with [this commit](https://github.com/zurb/foundation-sites/commit/6edc429b290999495d4071e18ae0080d62ea15cf).

Now that Foundation 6 is out, development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). So you can open any future issues there.
