### ISSUE TITLE
Off Canvas Overflow Issue

### ISSUE THREAD

**Issue by tdhartwick** [zurb/foundation-sites-6#327]
When the off canvas isn't visible and the body of the visible site is shorter than the off canvas' height, the page's height is the height of the off canvas.

This creates the whitespace at the bottom of sites occasionally.

**Comment by cwolfenberger1** [comment]
This also can create multiple scroll bars, as seen on the Foundation docs page!
![capture](https://cloud.githubusercontent.com/assets/12186383/11287276/943bb208-8ed7-11e5-9d63-882197972210.PNG)

**Comment by gakimball** [comment]
Fixed via 88e2af5306dde1c9d7b2c493b7aa7cdef0444932
