### ISSUE TITLE
Media Object image stacked

### ISSUE THREAD

**Issue by futurist** [zurb/foundation-sites-6#329]
http://foundation.zurb.com/sites/docs/media-object.html

2 media image stacked in above page, 
and I cannot upload image now,  later I'll show an image of the layout error

![2015-11-20_101334](https://cloud.githubusercontent.com/assets/159167/11290335/df4cae02-8f70-11e5-8258-70ac03bc67c0.png)

see above image, I'm in
XP Sp3+Chrome 45(32Bit)

**Comment by andycochran** [comment]
What's the error? These are nested media objects. The second one is supposed to be contained within the first.
