### ISSUE TITLE
Overlap main menu to code copy button in documentation

### ISSUE THREAD

**Issue by muhammadcahya** [zurb/foundation-sites-6#330]
![bug](https://cloud.githubusercontent.com/assets/4241620/11290911/67677640-8f6d-11e5-96c7-efa414ad5675.jpg)
Note :
Chrome
Firefox

Give same result

**Comment by gakimball** [comment]
Fixed with [this commit](https://github.com/zurb/foundation-sites/commit/c9f828e13810b1eeeca5649e4c17dafd8b0a926b).

Now that Foundation 6 is out, development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). So you can open any future issues there.
