### ISSUE TITLE
grid depends on global width (defined in different file)

### ISSUE THREAD

**Issue by erikmellum** [zurb/foundation-sites-6#331]
![image](https://cloud.githubusercontent.com/assets/6475033/11291084/755e935e-8ef1-11e5-95a7-2fb02a37ac7e.png)

**Comment by gakimball** [comment]
`global` should have been imported before `grid/grid`, which means the `$global-width` variable should be defined.

The framework is now designed to be imported all at once, since CSS exports are handled through `@include` statements.
