### ISSUE TITLE
Dropdown - hoverable

### ISSUE THREAD

**Issue by jiu** [zurb/foundation-sites-6#333]
Hello,

In the docs, the dropdown hoverable is not hoverable once you have clicked on it and then dropdown is visible when the mouse leave the button.

![image](https://cloud.githubusercontent.com/assets/777191/11297566/930e1b08-8f79-11e5-92ff-013ea5ea8ac3.png)

Thanks,
Jiu

**Comment by gakimball** [comment]
CC @zurbchris 

To recreate:
- Hover on the dropdown
- Click on the dropdown button

Now moving your mouse off the dropdown won't change the state, and moving your mouse back on the button will hide it. So the state is effectively reversed.

**Comment by gakimball** [comment]
Fixed with [this commit](https://github.com/zurb/foundation-sites/commit/ed0a147fc0f9934a4a4b74ae05e1ad2adbdf2ae9).

Now that Foundation 6 is out, development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). So you can open any future issues there.
