### ISSUE TITLE
Download Bug

### ISSUE THREAD

**Issue by amagdic** [zurb/foundation-sites-6#339]
ON URL: http://foundation.zurb.com/sites/download.html/

if you go over download buttons it displays ver. 5.5.3 not 6.0

update title atribute

**Comment by gakimball** [comment]
Opened an issue in the customizer's (private) codebase to address this.

Also, in the future, open all Foundation 6 issues in [zurb/foundation-sites](https://github.com/zurb/foundation-sites), as this repo will be closing soon.
