### ISSUE TITLE
Responsive Menu : Drilldown 2nd level + span bug

### ISSUE THREAD

**Issue by proov** [zurb/foundation-sites-6#340]
Hey :)

Double bug here.. sorry :D

Here is a code pen : http://s.codepen.io/proov/debug/EVqmPP

##### Span bug
In the responsive menu, in drilldown mode, when i have a `<span>` inside `<a>`, i have some strange click behavior.. I removed them and then i was able to click nicely on the links, to go to the 2nd level and go back.

##### 2nd level links
Strange bug here.. Still in drilldown mode, i can click on the root level links, but when i click on the 2nd level links (i didn't tried deeper levels), nothing happens... 

I did something wrong ?

Many thanks!! This feature is really impressive !

**Comment by gakimball** [comment]
Could you re-open this issue at [zurb/foundation-sites](https://github.com/zurb/foundation-sites)? This repo is closing in the next week. Thanks! :)
