### ISSUE TITLE
Button Group - Can't use .stacked-for-small and .expanded for the same group

### ISSUE THREAD

**Issue by mediamr** [zurb/foundation-sites-6#342]
If i use .stacked-for-small and .expanded for the same button group, the group is expanded, but the stacking-option for small is broken.
Problem: button group sticks with the calculated width on small (e.g. 4 items = 25% width)
Should be: stacked with 100% width

**Comment by gakimball** [comment]
Could you reopen this issue at [zurb/foundation-sites](https://github.com/zurb/foundation-sites)? This repo is being closed in the next week. Thanks! :)

**Comment by mediamr** [comment]
Done.
