### ISSUE TITLE
Unknown Off-canvas Issue, Simple Test Case

### ISSUE THREAD

**Issue by calmass** [zurb/foundation-sites-6#343]
I am having trouble getting off-canvas to work in a more complex test page.  There is no error in either Chrome or Firefox, and the screen goes semi-opaque as it is supposed to, the new classes are applied as they are supposed to (?!), but the content does not slide over as it's supposed to.  

I boiled everything down into a very simple test page, and then nothing happens at all.  Can I get another pair of eyes on this an tell me what is wrong with my simple test case?  Here is the page:

    <!doctype html>

    <%@ page contentType="text/html" pageEncoding="UTF-8" %>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
    <html lang="en">
    <head>
        <title>Hello</title>
        <link rel="stylesheet" href="/bower_components/foundation-sites/dist/foundation.min.css" >
    </head>

    <body>

            <div class="off-canvas-wrapper">
                <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
                    <div class="off-canvas position-left" id="offCanvas" data-off-canvas>Off-canvas!</div>
                    <div class="off-canvas-content" data-off-canvas-content>
                        <br/>
                        <br/>
                        <br/>
                        <button type="button" class="button" data-toggle="offCanvas">Open Menu</button>                        
                    </div>
                </div>
            </div>
        
        <script type="text/javascript" src="/bower_components/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="/bower_components/foundation-sites/dist/foundation.min.js">        </script>
        </body>

    </html>

Simply, nothing happens when I click the button to open the menu.  In the more complicated test case I was importing the specific js files, and in the simple I just imported everything.

Thank you,

**Comment by calmass** [comment]
I forgot to mention, I am updated to the latest versions of Chrome, Firefox, and Foundation-Sites (6.0.5).  This is running on a simple Tomcat 8 server.  I have tried with both JSP and HTML pages.

**Comment by rafibomb** [comment]
Thanks for the report! This is the private release repo. You can open this issue here to her addressed: https://github.com/zurb/foundation-sites
