### ISSUE TITLE
Foundation sites 6 javascript not working in production

### ISSUE THREAD

**Issue by iz5clj** [zurb/foundation-sites-6#348]
I have installed the zurb template:
`$ foundation new --framework sites --template zurb`

Running the watch task works perfectly:
`$ foundation watch`
I have added a simple tooltip, and everything is just fine.

Then I build for production:
`$ foundation build production`
And now javascript is not working.

What am I missing?

**Comment by gakimball** [comment]
Are you getting any JavaScript errors?

**Comment by gakimball** [comment]
Hey there, we're closing this repo today so we can track issues in the proper Foundation repo, which is zurb/foundation-sites. So I'm reopening this issue at zurb/foundation-sites#7664.
