### ISSUE TITLE
Order of Settings

### ISSUE THREAD

**Issue by di5abled** [zurb/foundation-sites-6#349]
Shouldn't be `$rem-base` before the first `rem-calc(...)` function?
Otherwise the first `rem-calc` uses the wrong `$rem-base`!?

This is currently wrong in your settings:
https://github.com/zurb/foundation-sites-6/blob/develop/scss/_settings.scss#L72
https://github.com/zurb/foundation-sites-6/blob/develop/scss/_settings.scss#L46

**Comment by gakimball** [comment]
We're discussing a solution at zurb/foundation-sites#7021
