### ISSUE TITLE
fields not responsive

### ISSUE THREAD

**Issue by tehlivi** [zurb/foundation-sites-6#350]
When putting fields in columns, they're not responsive. 

Example:
![screen shot 2015-12-15 at 10 02 19 am](https://cloud.githubusercontent.com/assets/5497842/11815774/f9d6a150-a312-11e5-8b78-9a7d9c3df829.png)

Fix: 
![screen shot 2015-12-15 at 10 02 08 am](https://cloud.githubusercontent.com/assets/5497842/11815777/fcec3f12-a312-11e5-9f2c-67e05559aa8e.png)

<pre>
.input-group-field{
    width: 100%;
}
</pre>

**Comment by gakimball** [comment]
Could you post the HTML for that screenshot?

**Comment by zurbrandon** [comment]
@gakimball could this be from the widths set on inputs in the Topbar?

**Comment by tehlivi** [comment]
Absolutely. Sorry about the wait.
 
    <form class="reservation-widget">
        <div class="row">
            <div class="medium-3 columns text-center">
                <div class="title">Reserve</div>
                Your stay today
            </div>
    
            <div class="medium-3 columns">
                <div class="input-group">
                    <input id="datepicker-arrive" class="input-group-field datepicker" placeholder="Arrival">
    
                    <div class="input-group-button">
                        <a id="datepicker-arrive-trigger" class="ui-datepicker-trigger"><i class="fa fa-calendar"></i></a>
                    </div>
                </div>
            </div>
    
            <div class="medium-3 columns">
                <div class="input-group">
                    <input id="datepicker-depart" class="input-group-field datepicker" placeholder="Departure">
    
                    <div class="input-group-button">
                        <a id="datepicker-depart-trigger" class="ui-datepicker-trigger"><i class="fa fa-calendar"></i></a>
                    </div>
                </div>
            </div>
    
            <div class="medium-3 columns reserve-field">
                <button type="submit" id="submit-reservation" class="button expanded">
                    <span class="text">Search</span>
                    <span class="float-right"><i class="fa fa-search"></i></span>
                </button>
            </div>
        </div>
    </form>

**Comment by gakimball** [comment]
Hey friend, thanks for the code sample. :) We need to close this repo today, so I'm reopening this issue at zurb/foundation-sites#7663, with your original screenshot and code sample.
