### ISSUE TITLE
WordPress integration

### ISSUE THREAD

**Issue by TheAggressive** [zurb/foundation-sites-6#37]
I'm looking to integrate with a WordPress theme. I checked the installation.html and it says to go to: http://foundation.zurb.com/sites/resources

When I arrive at that location, I'm greeted with a 404 screen.

How would I go about integrating with WordPress? Change the gulp settings? Any help will be useful!

Thanks!

**Comment by zurbrandon** [comment]
Looks like this is getting jammed on so i'll close this. Thnanks All!

**Comment by andycochran** [comment]
This. http://jointswp.com/ :+1:
