### ISSUE TITLE
[Toggler]  X  - CONTENT INTERFERES WITH UI,  ELEMENT NOT NOTICEABLE

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#52]
**How can we reproduce this bug?**

DOCS  > PLUGINS > TOGGLER

1. Mark As Closable and With Alternate Animation
2. Look at the X - Content very close around the X. Also area not well defined. Not really that visible.
3. N/A

**What did you expect to happen?**
Enough space around the X . Bring notice to it . After all it is an important UI element - requiring user action.

**What happened instead?**
Content too close to the UI element. Cluttered. UI element not noticeable enough.

See attached screen shot. 
There should be a nice even space around the X. Should be more noticeable

![mark-as-closable](https://cloud.githubusercontent.com/assets/14908417/10236948/6096ab54-6869-11e5-8666-2d5108550224.jpg)

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
We can update our docs to not have that visual bug, but that'll mostly be left up to the developer/designer to account for.
