### ISSUE TITLE
Terminal install issues - OS Mavericks

### ISSUE THREAD

**Issue by lucyland** [zurb/foundation-sites-6#57]
I've just attempted to install v6 using the terminal instructions from Github, and as expected there were issues with NPM errors—I thought I had Xcode installed and am admittedly not savvy with command lines. Two screen shots showing the installation process are attached.

![1](https://cloud.githubusercontent.com/assets/1000313/10253634/42d21e7a-68f3-11e5-851a-3e4e8a02bb85.jpg)
![2](https://cloud.githubusercontent.com/assets/1000313/10253635/42d56b8e-68f3-11e5-8c6b-fcc79b98d206.jpg)

**Comment by gakimball** [comment]
Foundation 6 development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). The next time you're looking at the framework, if you have any setup issues, open an issue there and we'll help you out. Thanks!

Also, now that the framework is out, you can scaffold a blank project and get started there.

```bash
npm install foundation-cli --global
foundation new
```
