### ISSUE TITLE
Accessibility Review: Accordion

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#59]
**Files:**
- [Documentation](https://github.com/zurb/foundation-sites-6/blob/master/docs/pages/accordion.md)
- [Sass code](https://github.com/zurb/foundation-sites-6/blob/master/scss/components/_accordion.scss)
- [JavaScript code](https://github.com/zurb/foundation-sites-6/blob/master/js/foundation.accordion.js)

**Features:**
- By default, it's your standard accordion. Clicking a pane opens the content, and closes the active pane.
- It can be configured so that multiple panes can be open at once.
- It can be configured so that every pane can be closed at once.

**To Implement:**
- We don't have keyboard support in there yet, as we need some input on it.
- The right ARIA attributes are on there, but eventually the plugin will automatically add them.

**Comment by zurbchris** [comment]
I think we've got it all in there now, so I'll close this down. If there's more that anyone thinks needs to be done, just reopen.
