### ISSUE TITLE
Feedback: Visual style

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#60]
We have a goal with Foundation 6 for the framework to simultaneously **look simpler** and also **look prettier**. Simpler means less CSS, less file size, less properties to override. Look prettier means it maybe works a little better for out-of-the-box UIs.

**We'd like feedback on the visual elements of the new framework.** With think we've been able to pull off simpler yet nicer-looking pretty well, but all feedback is welcome.

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
