### ISSUE TITLE
Starter project templates

### ISSUE THREAD

**Issue by OndrejVasicek** [zurb/foundation-sites-6#61]
To me, the chance to use Sass and Compass in in F4 and then the whole new workflow in F5, are the big reasons, why I love Foundation. I feel it has taught me a lot. I think it truly makes me a better developer.
So I was quite excited, what F6 was going to bring.

From docs I discovered 2 starter templates. Because the Cli doesn’t know them yet, I had to download them from Github. I hope it’s the right way to do it now.

My opinion is, that the Advanced template is another step farther. I it looks highly useful. The distribution between production and development, livereload server or the magical UnCSS, which could be a huge size reducer.

Actually for my F5 projects I tuned your Gruntfile to achieve a lot of stuff you showed here.
But there is a BIG BUT. The Advanced template is absolutely great. But it’s only for pure frontend devs, who “just” create their front and give it to another step in the chain. So far, so good.

But imagine, you are a front and backend dev as well. Or more specifically. Imagine, you’re working on living project, where you change the system every day. This is actually my daily reality. For me, the idea, that I have some frontend, which I had to fill with test data, export it and then transfer it to the real project full of PHP and templates, it’s absolutely crazy.

So I hoped, that basic template is gonna be something for me, but it’s not. It’s pure sass to css compiling. Here I have to ask – will it be useful for someone? Just compiling sass to css? I can’t imagine dev, who does just this.

I’m attaching my Gruntfile from F5 projects. It’s based on your F5 vanilla Grunt file and it works perfectly in running project with PHP framework (of course some paths are specific only for me). It’s not perfect, but does those things
* Compiles sass to css, compress it, creates sourceMaps and adds prefixes (autoprefixer) (I truly love the sass syntax, so don’t be confused, why there isn’t any scss folrders or files)
* Merges and compress all selected foundation js files and my own files, creates source maps
* Compress images into output folder
* Reload my page – I thing I use different approach – via the chrome plugin I can reload any page. I don’t run local server via the Grunt/gulp, because I have my own apache server – I need to run PHP, PostgreSQL, …
* Watcher of course

So apart from the UnCSS, which I’m afraid it’s not easily possible to use, when you have PHP templates (please tell me I’m wrong :) ), or the copying into build/production folders, which I don’t want to (I’m using php templates even through the development part), I thinkg it does pretty much the same. Of course with the grunt and with my shitty implementation.

So my suggesting is, that there really should be something like Advanced template for front end and Semi-Advanced template more like it was in F5. I believe, that there is a lot of devs, who just aren’t pure front end devs and use Foundation in their current system, where you have your own templates and partial templates and it’s not possible to export your frontend somewhere else and then copy some parts every time I need to do some change.

```javascript
module.exports = function (grunt) {
    require('jit-grunt')(grunt);


    var js_files = [
        'bower_components/foundation/js/foundation/foundation.js',
        //'bower_components/foundation/js/foundation/foundation.abide.js',
        //'bower_components/foundation/js/foundation/foundation.accordion.js',
        //'bower_components/foundation/js/foundation/foundation.alert.js',
        //'bower_components/foundation/js/foundation/foundation.clearing.js',
        //'bower_components/foundation/js/foundation/foundation.dropdown.js',
        //'bower_components/foundation/js/foundation/foundation.equalizer.js',
        //'bower_components/foundation/js/foundation/foundation.interchange.js',
        //'bower_components/foundation/js/foundation/foundation.joyride.js'
        //'bower_components/foundation/js/foundation/foundation.magellan.js',
        'bower_components/foundation/js/foundation/foundation.offcanvas.js',
        //'bower_components/foundation/js/foundation/foundation.orbit.js',
        //'bower_components/foundation/js/foundation/foundation.reveal.js',
        //'bower_components/foundation/js/foundation/foundation.slider.js',
        //'bower_components/foundation/js/foundation/foundation.tab.js',
        'bower_components/foundation/js/foundation/foundation.tooltip.js',
        //'bower_components/foundation/js/foundation/foundation.topbar.js'
        //'bower_components/foundation/js/vendor/placeholder.js',

        //'bower_components/slick-carousel/slick/slick.min.js',
        'js/_*.js',
        'js/app.js'
    ];


    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sass: {
            options: {
                includePaths: ['bower_components/foundation/scss', 'sass'],
                outputStyle: 'compressed',
                sourceMapContents: false,
                sourceComments: false,
                sourceMap: true
            },
            dist: {
                files: {
                    'css/app.css': 'sass/app.sass'
                }
            }
        },

        postcss: {
            options: {
                map: {
                    inline: false
                },
                processors: [
                    require('autoprefixer-core')({browsers: ['> 0.1% in CZ']})
                ]
            },
            dist: {
                src: 'css/app.css'
            }
        },

        uglify: {
            options: {
                sourceMap: true
            },
            dist: {
                files: {
                    'js/app.min.js': [js_files]
                }
            }
        },

        imagemin: {
            target: {
                files: [{
                    expand: true,
                    cwd: 'img-original/',
                    src: ['**/*.{jpg,gif,svg,jpeg,png,ico}'],
                    dest: 'img/'
                }]
            }
        },

        watch: {
            grunt: {files: ['Gruntfile.js']},

            sass: {
                files: 'sass/*.sass',
                tasks: ['sass', 'postcss']
            },

            js: {
                files: [js_files],
                tasks: ['uglify']
            },

            image: {
                files: ['img-original/*'],
                tasks: ['newer:imagemin']
            },

            livereload: {
                options: {
                    livereload: true
                },
                files: [
                    'css/app.css',
                    'js/app.min.js',
                    '../config/**',
                    '../controllers/**',
                    '../models/**',
                    '../views/**',
                    'index.html'
                ]
            }
        }
    });

    grunt.registerTask('build', [
        'uglify',
        'sass',
        "postcss",
        "newer:imagemin"
    ]);

    grunt.registerTask('default', [
        'build',
        'watch'
    ]);
};
```

**Comment by OndrejVasicek** [comment]
Having 3 templates can be truly too much. I’m suggesting to change the point of view, what kind of template we need. I honestly can’t think of person, who needs just transfer sass to css – the basic template. It doesn’t even cover the base Foundation functionality – what about the js?

I see it more like frontend devs template/the others devs template.

The advanced template is great for you guys. For the pure front end workflow. Just do some frontend and export it to other guy, who can implement it.

But there are a lot of people like me, who create and implement the work as well. But what’s more important – we need to work with foundation in already running project. There is no place for workflow like “src/dist”. We have our own systems and foundation is only one part of it.
We can appreciate every new feature you’ve brought to F6 (except the UnCSS, which I guess won’t work with php/other templates), but not in this way.

I hope I described it quite well in my original post. There is actually my edited version of Gruntfile from F5, which does almost the same what your new features in F6, but with the direct F5 way.

So for those people It’s quite impossible to use F6 now.

**Comment by gakimball** [comment]
@OndrejVasicek I see what you're saying, but the starter templates are for people who don't have their own stack already. If you do, we have a lot of different ways to get the code. There are complete/essential/custom CSS downloads; the Sass version will be on five package managers (npm, Bower, Meteor, Composer, NuGet); and the community has integrations for every possible MVC framework and CMS out there. There are a *lot* of ways to install Foundation into an existing project.

How do you think we can make it easier to install Foundation into an existing project? The myriad of different ways build systems work seems like it would make that hard to do.

**Comment by natecox** [comment]
@gakimball Not to derail, but do you have an expected date for the meteor package to be on atmosphere? Can I help with that in some way?

**Comment by gakimball** [comment]
@natecox Can you verify that our `package.js` is formatted properly? If it's not, you can submit a PR and we'll pull it in. Once that's set we can publish some kind of beta package.

**Comment by natecox** [comment]
@gakimball looks like it may need a bit of tweaking. I'll take a look at it this evening and issue a pull request when I get it working as a local package.

**Comment by natecox** [comment]
@gakimball I went ahead and issued a pull request for the meteor package, referenced above.

**Comment by gakimball** [comment]
Going to close this out as we have a clear picture of what we want out of our two templates.

As for developers integrating Foundation into their own build processes (which we know is many, many people), we want the documentation to be clear as possible regarding how to set up Sass import paths, what JavaScript files to include, dependencies, and so on. If any part of that process isn't obvious, let us know and we can clear it up in the documentation.
