### ISSUE TITLE
[Dropdown Menus] UI Issues & DOCS Enhancements / Usability

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#71]
**How can we reproduce this bug?**

1. DOCS - Drop Down Menus
See attached Screen shot of post in FEEDBACK REQUEST - VISUAL STYLE
I am posting here so there is a cross reference. I feel the details are important enough to report here.

**Test case**

https://github.com/zurb/foundation-sites-6/issues/60
![docs-drop-down-menus](https://cloud.githubusercontent.com/assets/14908417/10345602/1f32d934-6ce8-11e5-8a87-9e16a54a5cba.jpg)

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by tdhartwick** [comment]
Thanks @blynnc! We're currently working on changing how arrows function in F6, which should take care of this issue. We'll marked this as closed for now!
