### ISSUE TITLE
ACCORDIAN CONTAINER - VERTICAL AND HORIZONTAL TABS

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#89]
One thing I really miss --

Foundation 4 used to provide  stacked vertical tabs - Tabbed Side Bar. (see attached)  I use this type of thing a lot. In Foundation 4 this used to automatically convert to the standard accordian container on smaller screen widths. WHICH I THOUGHT WAS GREAT!

Now in 5 I have to manually add in another layer and more code to change to the stacked horizontal accordian on smaller screen widths.

Would be great if  this was easier.

(never mind the colors here - screen shot for reference)
![tabbed-side-bar](https://cloud.githubusercontent.com/assets/14908417/10373504/20c61ee6-6dab-11e5-839f-cd2f4a59ed25.jpg)

**Comment by wtsutton** [comment]
Is this what you are after?

    
    <ul class="tabs show-for-medium" data-tabs="data-tabs" id="example-tabs">
      <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Panel 1</a></li>
      <li class="tabs-title"><a href="#panel2">Panel 2</a></li>
      <li class="tabs-title"><a href="#panel3">Panel 3</a></li>
    </ul>
    <ul class="accordion tabs-content" data-tabs-content="example-tabs" 
             data-accordion="data-accordion" role="tablist">
      <li class="accordion-item is-active">
        
        <a class="show-for-small-only" href="#panel1" role="tab" class="accordion-title" 
                id="panel1-heading" aria-controls="panel1">Panel 1</a>
        
        <div id="panel1" class="accordion-content tabs-panel is-active" role="tabpanel" 
                  data-tab-content="data-tab-content" aria-labelledby="panel1-heading">
          <p>Panel 1. This is the first panel. This is the first panel. This is the first panel. 
                   This is the first panel.</p>
        </div>
      </li>
      <li class="accordion-item">
        
        <a class="show-for-small-only" href="#panel2" role="tab" class="accordion-title" 
                id="panel2-heading" aria-controls="panel2">Panel 2</a>
        
        <div id="panel2" class="accordion-content tabs-panel" role="tabpanel" 
                 data-tab-content="data-tab-content" aria-labelledby="panel2-heading">
          <p>Panel 2. This is the second panel. This is the second panel. This is the second panel. 
                    This is the second panel.</p>
        </div>
      </li>
      <li class="accordion-item">
        
        <a class="show-for-small-only" href="#panel3" role="tab" class="accordion-title" 
                   id="panel3-heading" aria-controls="panel3">Panel 3</a>
        
        <div id="panel3" class="accordion-content tabs-panel" role="tabpanel" 
                  data-tab-content="data-tab-content" aria-labelledby="panel3-heading">
          <p>Panel 3. This is the third panel. This is the third panel. This is the third panel. 
                   This is the third panel.</p>
        </div>
      </li>
    </ul>

I could do this on Foundation 5.4.2 but not 5.5.3 (except with a change to the tabs js)

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
