### ISSUE TITLE
Accessibility Review: Off-canvas

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#9]
**Files:**
- [Sass code](https://github.com/zurb/foundation-sites-6/blob/master/scss/components/_off-canvas.scss)
- [JavaScript code](https://github.com/zurb/foundation-sites-6/blob/master/js/foundation.offcanvas.js)

**Features:**
- The off-canvas is a generic off-screen panel that can be opened and closed with a click trigger (or programmatically by the developer). They're mostly used for navigation, but any content can be put inside.
- The menu itself gets `aria-hidden="true"`, any triggers that open the menu should get `aria-expanded="false"`.
- When the menu is opened, the menu gets `aria-hidden="false"` and the trigger that was clicked gets `aria-expanded="true"`. Focus shifts to the first `<a>` or `<button>` inside the menu.
- When the menu is closed, focus shifts to the element that last opened the menu.
- When the `esc` key is pressed while the menu is open, it closes.

**Questions:**
- Are any other ARIA elements necessary, like `aria-describedby` for the menu, or `aria-controls` for click triggers?
- Some designs require two sets of navigation (desktop/mobile), in which case you hide one set of navigation for AT, while some designs will use the off-canvas menu on mobile and desktop. (There's a CSS class you can add to make the menu always visible on larger screens.) What are your recommendations for properly hiding the off-canvas menu when it's closed?

**Comment by zurbchris** [comment]
It seems there *might* be a need to specify between focusable items, i.e. inputs, links, menuitems, etc, and programmatically set tabindex to -1 so they can't be focused until the offcanvas opens. This is overhead on the JS, three times, so I'm not wild about it. Other thoughts?

**Comment by klihelp** [comment]
> When the esc key is pressed while the menu is open, it closes.

Any though on this?

**Comment by chrismcintosh** [comment]
Is there any way to override the default behavior? 

I have an ajax form in my offcanvas I'd like to give it focus as soon as the canvas opens. Apart from that when I click in the input the focus automatically jumps to the close button and I have to click the input again. I've even tried setting a delay on the focus but no luck.

`
jQuery(document).ready(function ($) {

    $('#offCanvasRight').on('opened.zf.offcanvas', function() {
         setTimeout(function() {
              find('input[type="search"]').focus();
         }, 1200);
     });

});
`
