### ISSUE TITLE
Reveal: background overlay.

### ISSUE THREAD

**Issue by zurbchris** [zurb/foundation-sites-6#90]
Instead of each modal getting it’s own background, maybe generate one for the whole page if a modal is detected?

This would reduce the number of elements generated by the JS, but would make accessibility a bit more of a hassle.

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
